// AUTO-GENERATED by src/tft_tracker/lol_pipeline.py (--worker-rank-averages-out). Do not edit by hand.
export const RANK_AVERAGES_GENERATED_AT = "";
export interface RankAverage { n: number; metrics: Record<string, number>; }
export const RANK_AVERAGES: Record<string, Record<string, RankAverage>> = {};
