// BrokenMeta.gg service worker -- offline fallback + faster repeat visits.
// Regenerated by site_build/build_site.py; do not edit dist/sw.js by hand.
// v2: only successful (2xx) responses are ever cached -- v1 cached errors and
// error pages too, so a visitor who loaded the site mid-deploy or during an
// outage could be stuck on a broken page.
const CACHE = 'brokenmeta-v2';
const APP_SHELL = ['/', '/assets/css/style.css', '/favicon.svg'];

// Shown when the network is down and the exact page isn't cached. Deliberately
// NOT the home page: relative asset links only resolve at their own URL depth,
// so serving '/' under another URL renders an unstyled, mislinked page.
const OFFLINE_PAGE = '<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BrokenMeta.gg</title>'
  + '<style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#100b26;color:#f0e7d8;font-family:system-ui,sans-serif;text-align:center;padding:24px}'
  + 'h1{font-size:22px;margin:0 0 8px}p{margin:0 0 18px;color:#bdb4cf}a{color:#f0e7d8;background:#d72638;padding:10px 18px;text-decoration:none;font-weight:700}</style></head>'
  + '<body><div><h1>Site momentanément inaccessible</h1><p>Connexion impossible pour le moment. Réessaie dans un instant.<br>Site temporarily unreachable. Please try again shortly.</p>'
  + '<a href="/">BrokenMeta.gg</a></div></body></html>';

function cacheIfOk(req, res) {
  if (res && res.ok && res.type === 'basic') {
    const copy = res.clone(); // clone NOW: once the page reads the body, a later clone() throws
    caches.open(CACHE).then((cache) => cache.put(req, copy)).catch(() => {});
  }
  return res;
}

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(APP_SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return; // leave fonts CDN / analytics alone

  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => cacheIfOk(req, res))
        .catch(() => caches.match(req).then((cached) => cached || new Response(OFFLINE_PAGE, {
          status: 503, headers: { 'Content-Type': 'text/html; charset=utf-8' },
        })))
    );
    return;
  }

  event.respondWith(
    caches.match(req).then((cached) => {
      const fresh = fetch(req)
        .then((res) => cacheIfOk(req, res))
        .catch(() => cached || Response.error());
      return cached || fresh;
    })
  );
});
