// BrokenMeta.gg service worker -- offline fallback + faster repeat visits.
// Regenerated by site_build/build_site.py; do not edit dist/sw.js by hand.
const CACHE = 'brokenmeta-v1';
const APP_SHELL = ['/', '/assets/css/style.css', '/favicon.svg'];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(APP_SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return; // leave fonts CDN / analytics alone

  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => { caches.open(CACHE).then((cache) => cache.put(req, res.clone())); return res; })
        .catch(() => caches.match(req).then((cached) => cached || caches.match('/')))
    );
    return;
  }

  event.respondWith(
    caches.match(req).then((cached) => {
      const fresh = fetch(req)
        .then((res) => { caches.open(CACHE).then((cache) => cache.put(req, res.clone())); return res; })
        .catch(() => cached);
      return cached || fresh;
    })
  );
});
