-- BrokenMeta Weights: adds a "simulated DPS" score to item tooltips, using the stat weights the
-- brokenmeta.gg simulator computed for each spec (Weights.lua, generated by wow_addon_build.py).
local ADDON, ns = ...

local IS_FR = GetLocale() == "frFR"
local L = ns.Localize("core", {
  header = "BrokenMeta",
  vs_equipped = "vs équipé",
  same = "équipé",
  no_spec = "aucune spécialisation DPS simulée pour cette classe.",
  spec_set = "spécialisation : %s",
  spec_auto = "détection automatique (arbre de talents le plus rempli).",
  spec_unknown = "spécialisation inconnue : %s. Liste : /bmw list",
  help = "/bmw : fenêtre · /bmw weights · /bmw export · /bmw list · /bmw spec <id> · /bmw auto · /bmw minimap · /bmw share · /bmw ah · /bmw import · /bmw probe",
  weights = "Poids (DPS par point) pour %s :",
  approx = "approximation",
  share_state = "partage des données avec brokenmeta.gg : ",
  import_ok = "tes poids personnels sont importés : ils remplacent les poids génériques pour ce personnage.", import_bad = "ce texte n'est pas un export de poids BrokenMeta (il commence par BMW-W1).", import_class = "ces poids sont pour une autre classe que ce personnage.", import_cleared = "retour aux poids génériques (niveau 20).",
  refresh_weights = "tes poids personnels datent du niveau %d : refais-les sur brokenmeta.gg (Simuler mon personnage), à faire tous les %d niveaux.",
  loot_drop = "Butin de donjon : %s (%s)", loot_quest = "Récompense de quête : %s",
  welcome = {
    "merci d'avoir installé l'addon ! Clique sur le bouton à l'épée autour de la minicarte (ou tape /bmw) pour ouvrir le hub.",
    "Survole un objet : sa valeur en DPS pour ta spé s'affiche dans l'infobulle. Guides et simulateur : brokenmeta.gg",
  },
  update_available = "une nouvelle version de l'addon existe (%s, tu as la %s) : télécharge-la sur brokenmeta.gg (page WoW: Forever).",
  cant_wear = "ta classe ne peut pas le porter", wear_at = "portable au niveau %d",
  snap_done = "%d nouvelle(s) mesure(s) enregistrée(s).",
}, {
  header = "BrokenMeta",
  vs_equipped = "vs equipped",
  same = "equipped",
  no_spec = "no simulated DPS spec for this class.",
  spec_set = "spec: %s",
  spec_auto = "automatic detection (talent tree with the most points).",
  spec_unknown = "unknown spec: %s. List: /bmw list",
  help = "/bmw: window · /bmw weights · /bmw export · /bmw list · /bmw spec <id> · /bmw auto · /bmw minimap · /bmw share · /bmw ah · /bmw import · /bmw probe",
  weights = "Weights (DPS per point) for %s:",
  approx = "approximation",
  share_state = "data sharing with brokenmeta.gg: ",
  import_ok = "your personal weights are imported: they replace the generic weights for this character.", import_bad = "this text isn't a BrokenMeta weights export (it starts with BMW-W1).", import_class = "these weights are for another class than this character.", import_cleared = "back to the generic (level 20) weights.",
  refresh_weights = "your personal weights are from level %d: redo them on brokenmeta.gg (Simulate my character), every %d levels.",
  loot_drop = "Dungeon loot: %s (%s)", loot_quest = "Quest reward: %s",
  welcome = {
    "thanks for installing the addon! Click the sword button around the minimap (or type /bmw) to open the hub.",
    "Hover an item: its DPS value for your spec shows in the tooltip. Guides and simulator: brokenmeta.gg",
  },
  update_available = "a newer version of the addon exists (%s, you have %s): download it on brokenmeta.gg (WoW: Forever page).",
  cant_wear = "your class can't wear it", wear_at = "wearable at level %d",
  snap_done = "%d new measurement(s) recorded.",
})

local function say(msg) DEFAULT_CHAT_FRAME:AddMessage("|cff4fd1c5BrokenMeta|r " .. msg) end

---------------------------------------------------------------------------------------------
-- Spec selection
---------------------------------------------------------------------------------------------
local playerClass = select(2, UnitClass("player"))
local charKey = UnitName("player") .. "-" .. (GetRealmName() or "")
local currentSpec -- key into ns.WEIGHTS
local scoreCache = {}

local function classSpecs()
  local list = {}
  for id, s in pairs(ns.WEIGHTS) do
    if s.class == playerClass then list[#list + 1] = id end
  end
  table.sort(list, function(a, b)
    local sa, sb = ns.WEIGHTS[a], ns.WEIGHTS[b]
    if sa.tab ~= sb.tab then return sa.tab < sb.tab end
    return sa.role < sb.role -- "dps" before "tank" (Feral cat before bear)
  end)
  return list
end

local function specName(id)
  local s = ns.WEIGHTS[id]
  local n = s.name[IS_FR and "frFR" or "enUS"]
  if s.role == "tank" then n = n .. " (tank)" end
  return n
end

-- Forever uses the modern trait system (C_ClassTalents/C_Traits) with Classic-style trees. Its
-- node ids are the same TraitNode ids as the site's talent calculator, and Weights.lua maps each
-- one to its tree (ns.TALENT_TAB), so points per tree are counted from our own data.
-- Returns { [nodeID] = rank }, { tree1, tree2, tree3 } -- or nil if the API isn't there.
local function readTalents()
  local map = ns.TALENT_TAB and ns.TALENT_TAB[playerClass]
  if not map or not C_ClassTalents or not C_Traits or not C_Traits.GetNodeInfo then return nil end
  local ok, configID = pcall(C_ClassTalents.GetActiveConfigID)
  if not ok or not configID then return nil end
  local ranks, perTab = {}, { 0, 0, 0 }
  for nodeID, tab in pairs(map) do
    local ok2, info = pcall(C_Traits.GetNodeInfo, configID, nodeID)
    if ok2 and type(info) == "table" then
      local r = info.ranksPurchased or info.activeRank or info.currentRank or 0
      if r > 0 then
        ranks[nodeID] = r
        perTab[tab] = (perTab[tab] or 0) + r
      end
    end
  end
  return ranks, perTab
end
ns.readTalents = readTalents

-- Talent tree with the most points: modern traits first, then the legacy talent-tab API (its
-- return shape differs between client generations), then the modern specialization API.
local function talentTabWithMostPoints()
  local _, perTab = readTalents()
  if perTab then
    local best, bestPts = nil, 0
    for i, pts in ipairs(perTab) do
      if pts > bestPts then best, bestPts = i, pts end
    end
    if best then return best end
  end
  if GetNumTalentTabs and GetTalentTabInfo then
    local ok, n = pcall(GetNumTalentTabs)
    local best, bestPts = nil, 0
    for i = 1, (ok and n or 0) do
      local r = { pcall(GetTalentTabInfo, i) }
      if r[1] then
        local pts = type(r[4]) == "number" and r[4] or r[6]
        if type(pts) == "number" and pts > bestPts then best, bestPts = i, pts end
      end
    end
    if best then return best end
  end
  local getSpec = (C_SpecializationInfo and C_SpecializationInfo.GetSpecialization) or GetSpecialization
  if getSpec then
    local ok, idx = pcall(getSpec)
    if ok and type(idx) == "number" and idx >= 1 and idx <= 3 then return idx end
  end
  return nil
end

local function detectSpec()
  local list = classSpecs()
  if #list == 0 then return nil end
  local saved = BrokenMetaWeightsDB.chars[charKey]
  if saved and ns.WEIGHTS[saved] and ns.WEIGHTS[saved].class == playerClass then return saved end
  local tab = talentTabWithMostPoints()
  if tab then
    for _, id in ipairs(list) do
      if ns.WEIGHTS[id].tab == tab then return id end
    end
  end
  return list[1]
end

local function setSpec(id)
  currentSpec = id
  wipe(scoreCache)
end

---------------------------------------------------------------------------------------------
-- Rating -> percentage conversion
---------------------------------------------------------------------------------------------
-- Forever items carry Crit/Hit as ratings. Preferred source: the client itself. Fallback: 14 crit
-- rating / 10 hit rating per 1% -- read on Forever's item tooltips at level 60 AND measured in game
-- at level 6 by the addon itself (2026-09-26): Forever does not scale ratings with level.
local CR = {
  hit_melee = CR_HIT_MELEE or 6, hit_ranged = CR_HIT_RANGED or 7, hit_spell = CR_HIT_SPELL or 8,
  crit_melee = CR_CRIT_MELEE or 9, crit_ranged = CR_CRIT_RANGED or 10, crit_spell = CR_CRIT_SPELL or 11,
}
local L60 = { crit = 14, hit = 10 }
local ratingPerPct = {}

local function computeRatingPerPct(kind, cr)
  if GetCombatRatingBonusForCombatRatingValue then
    local ok, pct = pcall(GetCombatRatingBonusForCombatRatingValue, cr, 100)
    if ok and pct and pct > 0 then return 100 / pct, false end
  end
  if GetCombatRating and GetCombatRatingBonus then
    local ok1, rating = pcall(GetCombatRating, cr)
    local ok2, pct = pcall(GetCombatRatingBonus, cr)
    if ok1 and ok2 and rating and pct and rating > 0 and pct > 0 then return rating / pct, false end
  end
  return L60[kind], true
end

local function refreshRatings()
  local s = currentSpec and ns.WEIGHTS[currentSpec]
  local suffix = (s and s.caster) and "spell" or ((s and s.ranged) and "ranged" or "melee")
  for _, kind in ipairs({ "crit", "hit" }) do
    local v, approx = computeRatingPerPct(kind, CR[kind .. "_" .. suffix])
    ratingPerPct[kind] = v
    ratingPerPct[kind .. "_approx"] = approx
  end
  wipe(scoreCache)
end

---------------------------------------------------------------------------------------------
-- Item stats
---------------------------------------------------------------------------------------------
-- Forever runs the modern (Mainline) UI, where these globals moved into C_Item.
local GetStats = (C_Item and C_Item.GetItemStats) or GetItemStats
local GetItemInfo = (C_Item and C_Item.GetItemInfo) or GetItemInfo

-- GetItemStats keys -> our stat names. "phys"/"spell" suffixes only count for matching specs.
local STAT_KEYS = {
  ITEM_MOD_STRENGTH_SHORT = "str", ITEM_MOD_AGILITY_SHORT = "agi", ITEM_MOD_INTELLECT_SHORT = "int",
  ITEM_MOD_ATTACK_POWER_SHORT = "ap", ITEM_MOD_RANGED_ATTACK_POWER_SHORT = "rap",
  ITEM_MOD_SPELL_POWER_SHORT = "sp", ITEM_MOD_SPELL_DAMAGE_DONE_SHORT = "sp",
  ITEM_MOD_CRIT_RATING_SHORT = "critR", ITEM_MOD_CRIT_MELEE_RATING_SHORT = "critR_phys",
  ITEM_MOD_CRIT_RANGED_RATING_SHORT = "critR_phys", ITEM_MOD_CRIT_SPELL_RATING_SHORT = "critR_spell",
  ITEM_MOD_HIT_RATING_SHORT = "hitR", ITEM_MOD_HIT_MELEE_RATING_SHORT = "hitR_phys",
  ITEM_MOD_HIT_RANGED_RATING_SHORT = "hitR_phys", ITEM_MOD_HIT_SPELL_RATING_SHORT = "hitR_spell",
  ITEM_MOD_DAMAGE_PER_SECOND_SHORT = "wdps",
}

-- Classic-style "Equip:" lines that GetItemStats doesn't report. Matched on keywords (EN + FR)
-- rather than exact sentences so small wording differences between builds don't break them.
local scanTip = CreateFrame("GameTooltip", "BrokenMetaWeightsScanTip", nil, "GameTooltipTemplate")
scanTip:SetOwner(WorldFrame, "ANCHOR_NONE")
-- ASCII-only lowercase: string.lower follows the C locale and can mangle UTF-8 bytes (É, é...).
local function lower(s) return (s:gsub("[A-Z]", string.lower)) end
local EQUIP = lower(ITEM_SPELL_TRIGGER_ONEQUIP or "Equip:")

local function has(line, ...)
  for i = 1, select("#", ...) do
    if line:find(select(i, ...), 1, true) then return true end
  end
end

local function parseEquipLine(line, out)
  local isSpell = has(line, "spell", "sort")
  local pct = tonumber(line:match("(%d+)%s*%%"))
  local num = tonumber(line:match("(%d+)"))
  if not num then return end
  if has(line, "critical", "critique") then
    if pct then out[isSpell and "critP_spell" or "critP_phys"] = (out[isSpell and "critP_spell" or "critP_phys"] or 0) + pct
    else out[isSpell and "critR_spell" or "critR"] = (out[isSpell and "critR_spell" or "critR"] or 0) + num end
  elseif has(line, "chance to hit", "chances de toucher", "hit rating", "score de toucher") then
    if pct then out[isSpell and "hitP_spell" or "hitP_phys"] = (out[isSpell and "hitP_spell" or "hitP_phys"] or 0) + pct
    else out[isSpell and "hitR_spell" or "hitR"] = (out[isSpell and "hitR_spell" or "hitR"] or 0) + num end
  elseif has(line, "ranged attack power", "puissance d'attaque à distance") then
    out.rap = (out.rap or 0) + num
  elseif has(line, "attack power", "puissance d'attaque") then
    out.ap = (out.ap or 0) + num
  elseif has(line, "damage and healing", "dégâts et les soins", "dégâts et soins")
      and has(line, "magical", "magiques") then
    out.sp = (out.sp or 0) + num
  end
end

local function itemStats(link)
  local out = {}
  local ok, stats = pcall(GetStats, link)
  if ok and stats then
    for k, v in pairs(stats) do
      local key = STAT_KEYS[k]
      if key then out[key] = (out[key] or 0) + v end
    end
  end
  -- Only fall back to text for stat families GetItemStats said nothing about (no double count).
  local fromApi = {
    ap = out.ap or out.rap, sp = out.sp,
    crit = out.critR or out.critR_phys or out.critR_spell,
    hit = out.hitR or out.hitR_phys or out.hitR_spell,
  }
  scanTip:ClearLines()
  scanTip:SetHyperlink(link)
  local text = {}
  for i = 2, scanTip:NumLines() do
    local fs = _G["BrokenMetaWeightsScanTipTextLeft" .. i]
    local line = fs and fs:GetText()
    if line then
      line = lower(line)
      if line:find(EQUIP, 1, true) == 1 then parseEquipLine(line, text) end
      if not out.wdps and has(line, "per second", "par seconde") then
        local n = line:match("%(([%d%.,]+)")
        if n then text.wdps = tonumber((n:gsub(",", "."))) end
      end
    end
  end
  for k, v in pairs(text) do
    local family = (k:match("^crit") and "crit") or (k:match("^hit") and "hit") or (k == "rap" and "ap") or k
    if k == "wdps" then family = "wdps_text" end
    if not fromApi[family] then out[k] = (out[k] or 0) + v end
  end
  return out
end

-- Simulated DPS this item's stats are worth for the current spec (linear stat weights).
local RANGED_LOCS = { INVTYPE_RANGED = true, INVTYPE_RANGEDRIGHT = true, INVTYPE_THROWN = true }
local MAIN_LOCS = { INVTYPE_WEAPON = true, INVTYPE_WEAPONMAINHAND = true, INVTYPE_2HWEAPON = true }

-- Weapon DPS only counts for the weapon the simulator actually swings for this spec: ranged for
-- Hunters (Auto Shot), main hand / off hand for melee specs, nothing for casters.
local function weaponWeight(w, equipLoc)
  if RANGED_LOCS[equipLoc] then return w.wdps_r or 0 end
  if equipLoc == "INVTYPE_WEAPONOFFHAND" then return w.wdps_oh or 0 end
  if MAIN_LOCS[equipLoc] then return w.wdps_mh or 0 end
  return 0
end

-- Simulated DPS a stat table is worth for the current spec. Keys: str agi int ap rap sp,
-- critR/hitR (ratings, generic or _phys/_spell), critP/hitP (percent), wdps (weapon DPS).
-- Personal weights imported from the site ("Simulate my character", computed at the player's real
-- level and gear) replace the generic level-20 BiS weights for that character and spec.
local WEIGHT_KEYS = { "str", "agi", "int", "ap", "sp", "crit", "hit", "wdps_mh", "wdps_oh", "wdps_r" }

function ns.ActiveWeights(spec)
  local custom = BrokenMetaWeightsDB and BrokenMetaWeightsDB.custom and BrokenMetaWeightsDB.custom[charKey]
  if custom and custom.spec == spec then return custom.w, custom end
  return ns.WEIGHTS[spec] and ns.WEIGHTS[spec].w, nil
end

-- "BMW-W1;spec=shaman_enhancement;level=34;date=2026-09-26;str=0.139;..." -> true | false, error key
function ns.ImportWeights(text)
  text = (text or ""):gsub("%s", "")
  if text:sub(1, 6) ~= "BMW-W1" then return false, "import_bad" end
  local f = {}
  for k, v in text:gmatch("([%w_]+)=([^;]+)") do f[k] = v end
  local spec = f.spec
  if not spec or not ns.WEIGHTS[spec] or ns.WEIGHTS[spec].class ~= playerClass then return false, "import_class" end
  local w = {}
  for _, k in ipairs(WEIGHT_KEYS) do
    local v = tonumber(f[k] or "0")
    if not v or v < 0 or v > 100 then return false, "import_bad" end
    w[k] = v
  end
  BrokenMetaWeightsDB.custom = BrokenMetaWeightsDB.custom or {}
  BrokenMetaWeightsDB.custom[charKey] = { spec = spec, level = tonumber(f.level), date = f.date, w = w }
  BrokenMetaWeightsDB.chars[charKey] = spec
  currentSpec = spec
  wipe(scoreCache)
  if ns.OnDataChanged then ns.OnDataChanged() end
  return true
end

-- Imported weights are refreshed every REFRESH_LEVELS levels (stats and spell ranks change as the
-- character levels up). Returns the imported level when they are that old, else nil.
ns.REFRESH_LEVELS = 5
function ns.ImportedWeightsStale()
  local custom = BrokenMetaWeightsDB and BrokenMetaWeightsDB.custom and BrokenMetaWeightsDB.custom[charKey]
  if not custom or not custom.level then return nil end
  if (UnitLevel("player") or 0) - custom.level >= ns.REFRESH_LEVELS then return custom.level end
  return nil
end

function ns.ClearImportedWeights()
  if BrokenMetaWeightsDB.custom then BrokenMetaWeightsDB.custom[charKey] = nil end
  wipe(scoreCache)
  if ns.OnDataChanged then ns.OnDataChanged() end
end

local function scoreStats(st, equipLoc)
  if not currentSpec or not st then return nil end
  local s = ns.WEIGHTS[currentSpec]
  local w = ns.ActiveWeights(currentSpec)
  local own = s.caster and "spell" or "phys"
  local critR = (st.critR or 0) + (st["critR_" .. own] or 0)
  local hitR = (st.hitR or 0) + (st["hitR_" .. own] or 0)
  local critP = (st["critP_" .. own] or 0) + critR / ratingPerPct.crit
  local hitP = (st["hitP_" .. own] or 0) + hitR / ratingPerPct.hit
  local ap = (st.ap or 0) + (s.ranged and (st.rap or 0) or 0)
  return (st.str or 0) * w.str + (st.agi or 0) * w.agi + (st.int or 0) * w.int
    + ap * w.ap + (st.sp or 0) * w.sp + critP * w.crit + hitP * w.hit
    + (st.wdps or 0) * weaponWeight(w, equipLoc)
end

local function score(link)
  if not currentSpec or not link then return nil end
  local cached = scoreCache[link]
  if cached then return cached end
  local total = scoreStats(itemStats(link), select(9, GetItemInfo(link)))
  scoreCache[link] = total
  return total
end

---------------------------------------------------------------------------------------------
-- Can the player wear it? (armor/weapon type + level, from the beta client's own tables)
---------------------------------------------------------------------------------------------
local SUBCLASS_TYPES = {
  [4] = { [1] = "Cloth", [2] = "Leather", [3] = "Mail", [4] = "Plate Mail", [6] = "Shield" },
  [2] = { [0] = "Axes", [1] = "Two-Handed Axes", [2] = "Bows", [3] = "Guns", [4] = "Maces",
    [5] = "Two-Handed Maces", [6] = "Polearms", [7] = "Swords", [8] = "Two-Handed Swords",
    [10] = "Staves", [13] = "Fist Weapons", [15] = "Daggers", [16] = "Thrown", [18] = "Crossbows", [19] = "Wands" },
}
local KNOWN_TYPES = {}
for _, map in pairs(SUBCLASS_TYPES) do for _, t in pairs(map) do KNOWN_TYPES[t] = true end end

-- Returns canWear, levelNeeded. Types outside the table (rings, necks, trinkets) are always fine.
function ns.CanWearType(typeKey)
  if not typeKey or not KNOWN_TYPES[typeKey] or not ns.PROFICIENCY then return true, 0 end
  local p = ns.PROFICIENCY[playerClass]
  if not p then return true, 0 end
  local need = p[typeKey]
  if need == nil then return false, nil end
  return (UnitLevel("player") or 1) >= need, need
end

function ns.CanWearLink(link)
  local classID, subID = select(12, GetItemInfo(link))
  local map = SUBCLASS_TYPES[classID]
  return ns.CanWearType(map and map[subID])
end

-- Dungeon loot index (Data.lua): item id -> loot record.
local LOOT_BY_ID = {}
for _, it in ipairs(ns.LOOT or {}) do LOOT_BY_ID[it.id] = it end
ns.LOOT_BY_ID = LOOT_BY_ID

---------------------------------------------------------------------------------------------
-- Comparison with equipped gear
---------------------------------------------------------------------------------------------
local SLOTS = {
  INVTYPE_HEAD = { 1 }, INVTYPE_NECK = { 2 }, INVTYPE_SHOULDER = { 3 }, INVTYPE_CHEST = { 5 },
  INVTYPE_ROBE = { 5 }, INVTYPE_WAIST = { 6 }, INVTYPE_LEGS = { 7 }, INVTYPE_FEET = { 8 },
  INVTYPE_WRIST = { 9 }, INVTYPE_HAND = { 10 }, INVTYPE_FINGER = { 11, 12 },
  INVTYPE_TRINKET = { 13, 14 }, INVTYPE_CLOAK = { 15 }, INVTYPE_WEAPON = { 16, 17 },
  INVTYPE_2HWEAPON = { 16 }, INVTYPE_WEAPONMAINHAND = { 16 }, INVTYPE_WEAPONOFFHAND = { 17 },
  INVTYPE_SHIELD = { 17 }, INVTYPE_HOLDABLE = { 17 }, INVTYPE_RANGED = { 18 },
  INVTYPE_RANGEDRIGHT = { 18 }, INVTYPE_THROWN = { 18 }, INVTYPE_RELIC = { 18 },
}

-- Returns the delta against the weakest equipped item in the matching slot(s) (an empty slot
-- counts as 0), or nil + "same" when the hovered item is the one already equipped.
local function deltaVsEquipped(link, itemScore)
  local equipLoc = select(9, GetItemInfo(link))
  local slots = equipLoc and SLOTS[equipLoc]
  if not slots then return nil end
  local worst
  for _, slot in ipairs(slots) do
    local eq = GetInventoryItemLink("player", slot)
    if eq == link then return nil, true end
    local v = eq and score(eq) or 0
    if not worst or v < worst then worst = v end
  end
  return itemScore - worst
end

---------------------------------------------------------------------------------------------
-- Tooltip
---------------------------------------------------------------------------------------------
local function lootLine(link)
  local id = tonumber(link:match("item:(%d+)"))
  local it = id and LOOT_BY_ID[id]
  if not it then return nil end
  local dg = ns.DUNGEONS and ns.DUNGEONS[it.d]
  local dname = dg and (dg.name[IS_FR and "frFR" or "enUS"] or dg.name.enUS) or "?"
  if it.quest then return string.format(L.loot_quest, dname) end
  return string.format(L.loot_drop, dname, it.src or "?")
end

local function onTooltipItem(tt)
  if tt == scanTip or not currentSpec or not tt.GetItem then return end
  local _, link = tt:GetItem()
  local equipLoc = link and select(9, GetItemInfo(link))
  if not equipLoc or equipLoc == "" then return end
  local added = false
  local v = score(link)
  if v and v > 0 then
    local line = string.format("%s · %s : |cffffffff~%.2f DPS|r", L.header, specName(currentSpec), v)
    local canWear, need = ns.CanWearLink(link)
    if not canWear then
      line = line .. "  |cffff5050(" .. (need and string.format(L.wear_at, need) or L.cant_wear) .. ")|r"
    else
      local d, same = deltaVsEquipped(link, v)
      if same then
        line = line .. "  |cff888888(" .. L.same .. ")|r"
      elseif d then
        local color = d > 0.005 and "|cff40ff40+" or (d < -0.005 and "|cffff5050" or "|cffcccccc")
        line = line .. string.format("  %s%.2f|r %s", color, d, L.vs_equipped)
      end
    end
    tt:AddLine(line, 0.31, 0.82, 0.77)
    added = true
  end
  local src = lootLine(link)
  if src then
    tt:AddLine("|cff888888" .. src .. "|r")
    added = true
  end
  if added then tt:Show() end
end

if TooltipDataProcessor and Enum and Enum.TooltipDataType and Enum.TooltipDataType.Item then
  TooltipDataProcessor.AddTooltipPostCall(Enum.TooltipDataType.Item, onTooltipItem)
else
  for _, name in ipairs({ "GameTooltip", "ItemRefTooltip", "ShoppingTooltip1", "ShoppingTooltip2" }) do
    local tt = _G[name]
    if tt then tt:HookScript("OnTooltipSetItem", onTooltipItem) end
  end
end

---------------------------------------------------------------------------------------------
-- Slash commands
---------------------------------------------------------------------------------------------
local function printWeights()
  if not currentSpec then return say(L.no_spec) end
  local w = ns.WEIGHTS[currentSpec].w
  say(string.format(L.weights, specName(currentSpec)))
  local approx = ratingPerPct.crit_approx and (" (" .. L.approx .. ")") or ""
  say(string.format("  Str %.3f · Agi %.3f · Int %.3f · AP %.3f · SP %.3f", w.str, w.agi, w.int, w.ap, w.sp))
  say(string.format("  Crit 1%% %.3f (= %.1f rating) · Hit 1%% %.3f (= %.1f rating)%s",
    w.crit, ratingPerPct.crit, w.hit, ratingPerPct.hit, approx))
end

SLASH_BROKENMETAWEIGHTS1 = "/bmw"
SlashCmdList.BROKENMETAWEIGHTS = function(msg)
  local cmd, arg = (msg or ""):lower():match("^(%S*)%s*(.-)$")
  if cmd == "list" then
    for _, id in ipairs(classSpecs()) do
      say(string.format("  %s%s = %s", id == currentSpec and "> " or "", id, specName(id)))
    end
  elseif cmd == "spec" then
    if ns.WEIGHTS[arg] and ns.WEIGHTS[arg].class == playerClass then
      BrokenMetaWeightsDB.chars[charKey] = arg
      ns.ChooseSpec(arg)
      say(string.format(L.spec_set, specName(arg)))
    else
      say(string.format(L.spec_unknown, arg))
    end
  elseif cmd == "auto" then
    BrokenMetaWeightsDB.chars[charKey] = nil
    setSpec(detectSpec()); refreshRatings()
    if ns.OnDataChanged then ns.OnDataChanged() end
    say(L.spec_auto .. " " .. string.format(L.spec_set, currentSpec and specName(currentSpec) or "-"))
  elseif cmd == "weights" then
    printWeights()
  elseif cmd == "probe" then
    -- Which talent/spec APIs this client exposes (Forever mixes Classic data with the modern UI).
    for _, name in ipairs({ "GetNumTalentTabs", "GetTalentTabInfo", "GetTalentInfo", "C_ClassTalents",
        "C_Traits", "C_SpecializationInfo", "GetSpecialization", "GetCombatRatingBonusForCombatRatingValue",
        "GetCombatRatingBonus", "C_Container", "C_Item", "C_AuctionHouse", "QueryAuctionItems",
        "GetAuctionItemInfo", "GetManaRegen", "UnitCreatureFamily" }) do
      say(string.format("  %s: %s", name, _G[name] and type(_G[name]) or "|cffff5050nil|r"))
    end
    local _, perTab = readTalents()
    if C_AuctionHouse then say("  C_AuctionHouse.ReplicateItems: " .. type(C_AuctionHouse.ReplicateItems)) end
    say("  auction scan mode: " .. tostring(ns.AuctionMode and ns.AuctionMode()))
    say("  points per tree: " .. (perTab and table.concat(perTab, " / ") or "nil")
      .. " -> tree " .. tostring(talentTabWithMostPoints()))
  elseif cmd == "share" then
    if arg == "on" or arg == "off" then BrokenMetaWeightsDB.share = (arg == "on") end
    say(L.share_state .. (BrokenMetaWeightsDB.share and "|cff40ff40ON|r" or "off"))
    if ns.OnDataChanged then ns.OnDataChanged() end
  elseif cmd == "import" then
    if arg == "clear" then
      ns.ClearImportedWeights()
      say(L.import_cleared)
    elseif ns.ShowImportDialog then
      ns.ShowImportDialog()
    end
  elseif cmd == "copy" and ns.ShowShareCopy then
    ns.ShowShareCopy()
  elseif cmd == "ah" and ns.StartAuctionScan then
    ns.StartAuctionScan()
  elseif cmd == "snap" and ns.SnapshotAll then
    say(string.format(L.snap_done, ns.SnapshotAll()))
  elseif cmd == "minimap" and ns.ToggleMinimap then
    ns.ToggleMinimap()
  elseif cmd == "export" and ns.ShowExport then
    ns.ShowExport()
  elseif cmd == "" and ns.ToggleHub then
    ns.ToggleHub()
  else
    say(L.help)
  end
end

---------------------------------------------------------------------------------------------
-- Events
---------------------------------------------------------------------------------------------
local f = CreateFrame("Frame")
-- pcall: registering an event this client doesn't know raises an error on modern clients.
for _, ev in ipairs({ "PLAYER_LOGIN", "PLAYER_LEVEL_UP", "PLAYER_EQUIPMENT_CHANGED", "BAG_UPDATE_DELAYED",
    "CHARACTER_POINTS_CHANGED", "TRAIT_CONFIG_UPDATED", "PLAYER_TALENT_UPDATE" }) do
  pcall(f.RegisterEvent, f, ev)
end
f:SetScript("OnEvent", function(_, event)
  if event == "BAG_UPDATE_DELAYED" then
    -- only the hub cares about bag contents
  elseif event == "PLAYER_LOGIN" then
    BrokenMetaWeightsDB = BrokenMetaWeightsDB or {}
    BrokenMetaWeightsDB.chars = BrokenMetaWeightsDB.chars or {}
    setSpec(detectSpec())
    refreshRatings()
    C_Timer.After(10, function()
      local old = ns.ImportedWeightsStale()
      if old then say(string.format(L.refresh_weights, old, ns.REFRESH_LEVELS)) end
    end)
  elseif event == "PLAYER_LEVEL_UP" then
    if not BrokenMetaWeightsDB.chars[charKey] then setSpec(detectSpec()) end
    -- UnitLevel is updated just after the event fires.
    C_Timer.After(1, function()
      local old = ns.ImportedWeightsStale()
      if old then say(string.format(L.refresh_weights, old, ns.REFRESH_LEVELS)) end
    end)
    refreshRatings()
  elseif event == "PLAYER_EQUIPMENT_CHANGED" then
    refreshRatings() -- equipped rating changes can refine the rating->% measurement
  elseif not BrokenMetaWeightsDB.chars[charKey] then
    setSpec(detectSpec())
    refreshRatings()
  else
    refreshRatings()
  end
  if ns.OnDataChanged then ns.OnDataChanged() end
end)

---------------------------------------------------------------------------------------------
-- Shared with Hub.lua
---------------------------------------------------------------------------------------------
ns.L, ns.IS_FR, ns.say = L, IS_FR, say
ns.SLOTS = SLOTS
ns.score, ns.deltaVsEquipped, ns.itemStats, ns.scoreStats = score, deltaVsEquipped, itemStats, scoreStats
ns.classSpecs, ns.specName = classSpecs, specName
ns.GetItemInfo = GetItemInfo
function ns.GetSpec() return currentSpec end
function ns.GetRatingPerPct() return ratingPerPct end
function ns.PlayerClass() return playerClass end
function ns.ChooseSpec(id)
  BrokenMetaWeightsDB.chars[charKey] = id
  setSpec(id); refreshRatings()
  if ns.OnDataChanged then ns.OnDataChanged() end
end
