-- BrokenMeta Weights: adds a "simulated DPS" score to item tooltips, using the stat weights the
-- brokenmeta.gg simulator computed for each spec (Weights.lua, generated by wow_addon_build.py).
local ADDON, ns = ...

local IS_FR = GetLocale() == "frFR"
local L = IS_FR and {
  header = "BrokenMeta",
  vs_equipped = "vs équipé",
  same = "équipé",
  no_spec = "aucune spécialisation DPS simulée pour cette classe.",
  spec_set = "spécialisation : %s",
  spec_auto = "détection automatique (arbre de talents le plus rempli).",
  spec_unknown = "spécialisation inconnue : %s. Liste : /bmw list",
  help = "/bmw : fenêtre · /bmw weights · /bmw export · /bmw list · /bmw spec <id> · /bmw auto · /bmw minimap · /bmw probe",
  weights = "Poids (DPS par point) pour %s :",
  approx = "approximation",
} or {
  header = "BrokenMeta",
  vs_equipped = "vs equipped",
  same = "equipped",
  no_spec = "no simulated DPS spec for this class.",
  spec_set = "spec: %s",
  spec_auto = "automatic detection (talent tree with the most points).",
  spec_unknown = "unknown spec: %s. List: /bmw list",
  help = "/bmw: window · /bmw weights · /bmw export · /bmw list · /bmw spec <id> · /bmw auto · /bmw minimap · /bmw probe",
  weights = "Weights (DPS per point) for %s:",
  approx = "approximation",
}

local function say(msg) DEFAULT_CHAT_FRAME:AddMessage("|cff4fd1c5BrokenMeta|r " .. msg) end

---------------------------------------------------------------------------------------------
-- Spec selection
---------------------------------------------------------------------------------------------
local playerClass = select(2, UnitClass("player"))
local charKey = UnitName("player") .. "-" .. (GetRealmName() or "")
local currentSpec -- key into ns.WEIGHTS
local scoreCache = {}

local function classSpecs()
  local list = {}
  for id, s in pairs(ns.WEIGHTS) do
    if s.class == playerClass then list[#list + 1] = id end
  end
  table.sort(list, function(a, b)
    local sa, sb = ns.WEIGHTS[a], ns.WEIGHTS[b]
    if sa.tab ~= sb.tab then return sa.tab < sb.tab end
    return sa.role < sb.role -- "dps" before "tank" (Feral cat before bear)
  end)
  return list
end

local function specName(id)
  local s = ns.WEIGHTS[id]
  local n = s.name[IS_FR and "frFR" or "enUS"]
  if s.role == "tank" then n = n .. " (tank)" end
  return n
end

-- Forever uses the modern trait system (C_ClassTalents/C_Traits) with Classic-style trees. Its
-- node ids are the same TraitNode ids as the site's talent calculator, and Weights.lua maps each
-- one to its tree (ns.TALENT_TAB), so points per tree are counted from our own data.
-- Returns { [nodeID] = rank }, { tree1, tree2, tree3 } -- or nil if the API isn't there.
local function readTalents()
  local map = ns.TALENT_TAB and ns.TALENT_TAB[playerClass]
  if not map or not C_ClassTalents or not C_Traits or not C_Traits.GetNodeInfo then return nil end
  local ok, configID = pcall(C_ClassTalents.GetActiveConfigID)
  if not ok or not configID then return nil end
  local ranks, perTab = {}, { 0, 0, 0 }
  for nodeID, tab in pairs(map) do
    local ok2, info = pcall(C_Traits.GetNodeInfo, configID, nodeID)
    if ok2 and type(info) == "table" then
      local r = info.ranksPurchased or info.activeRank or info.currentRank or 0
      if r > 0 then
        ranks[nodeID] = r
        perTab[tab] = (perTab[tab] or 0) + r
      end
    end
  end
  return ranks, perTab
end
ns.readTalents = readTalents

-- Talent tree with the most points: modern traits first, then the legacy talent-tab API (its
-- return shape differs between client generations), then the modern specialization API.
local function talentTabWithMostPoints()
  local _, perTab = readTalents()
  if perTab then
    local best, bestPts = nil, 0
    for i, pts in ipairs(perTab) do
      if pts > bestPts then best, bestPts = i, pts end
    end
    if best then return best end
  end
  if GetNumTalentTabs and GetTalentTabInfo then
    local ok, n = pcall(GetNumTalentTabs)
    local best, bestPts = nil, 0
    for i = 1, (ok and n or 0) do
      local r = { pcall(GetTalentTabInfo, i) }
      if r[1] then
        local pts = type(r[4]) == "number" and r[4] or r[6]
        if type(pts) == "number" and pts > bestPts then best, bestPts = i, pts end
      end
    end
    if best then return best end
  end
  local getSpec = (C_SpecializationInfo and C_SpecializationInfo.GetSpecialization) or GetSpecialization
  if getSpec then
    local ok, idx = pcall(getSpec)
    if ok and type(idx) == "number" and idx >= 1 and idx <= 3 then return idx end
  end
  return nil
end

local function detectSpec()
  local list = classSpecs()
  if #list == 0 then return nil end
  local saved = BrokenMetaWeightsDB.chars[charKey]
  if saved and ns.WEIGHTS[saved] and ns.WEIGHTS[saved].class == playerClass then return saved end
  local tab = talentTabWithMostPoints()
  if tab then
    for _, id in ipairs(list) do
      if ns.WEIGHTS[id].tab == tab then return id end
    end
  end
  return list[1]
end

local function setSpec(id)
  currentSpec = id
  wipe(scoreCache)
end

---------------------------------------------------------------------------------------------
-- Rating -> percentage conversion
---------------------------------------------------------------------------------------------
-- Forever items carry Crit/Hit as ratings. Preferred source: the client itself (exact at any
-- level). Fallback: 14 crit rating / 10 hit rating per 1% at level 60 -- read on Forever's own
-- item tooltips -- scaled down for lower levels with the Burning Crusade formula (level-8)/52,
-- which is an ASSUMPTION for Forever, not a confirmed value.
local CR = {
  hit_melee = CR_HIT_MELEE or 6, hit_ranged = CR_HIT_RANGED or 7, hit_spell = CR_HIT_SPELL or 8,
  crit_melee = CR_CRIT_MELEE or 9, crit_ranged = CR_CRIT_RANGED or 10, crit_spell = CR_CRIT_SPELL or 11,
}
local L60 = { crit = 14, hit = 10 }
local ratingPerPct = {}

local function computeRatingPerPct(kind, cr)
  if GetCombatRatingBonusForCombatRatingValue then
    local ok, pct = pcall(GetCombatRatingBonusForCombatRatingValue, cr, 100)
    if ok and pct and pct > 0 then return 100 / pct, false end
  end
  if GetCombatRating and GetCombatRatingBonus then
    local ok1, rating = pcall(GetCombatRating, cr)
    local ok2, pct = pcall(GetCombatRatingBonus, cr)
    if ok1 and ok2 and rating and pct and rating > 0 and pct > 0 then return rating / pct, false end
  end
  local level = UnitLevel("player") or 60
  local scale = math.max(1, level - 8) / 52
  return L60[kind] * math.min(1, scale), true
end

local function refreshRatings()
  local s = currentSpec and ns.WEIGHTS[currentSpec]
  local suffix = (s and s.caster) and "spell" or ((s and s.ranged) and "ranged" or "melee")
  for _, kind in ipairs({ "crit", "hit" }) do
    local v, approx = computeRatingPerPct(kind, CR[kind .. "_" .. suffix])
    ratingPerPct[kind] = v
    ratingPerPct[kind .. "_approx"] = approx
  end
  wipe(scoreCache)
end

---------------------------------------------------------------------------------------------
-- Item stats
---------------------------------------------------------------------------------------------
-- Forever runs the modern (Mainline) UI, where these globals moved into C_Item.
local GetStats = (C_Item and C_Item.GetItemStats) or GetItemStats
local GetItemInfo = (C_Item and C_Item.GetItemInfo) or GetItemInfo

-- GetItemStats keys -> our stat names. "phys"/"spell" suffixes only count for matching specs.
local STAT_KEYS = {
  ITEM_MOD_STRENGTH_SHORT = "str", ITEM_MOD_AGILITY_SHORT = "agi", ITEM_MOD_INTELLECT_SHORT = "int",
  ITEM_MOD_ATTACK_POWER_SHORT = "ap", ITEM_MOD_RANGED_ATTACK_POWER_SHORT = "rap",
  ITEM_MOD_SPELL_POWER_SHORT = "sp", ITEM_MOD_SPELL_DAMAGE_DONE_SHORT = "sp",
  ITEM_MOD_CRIT_RATING_SHORT = "critR", ITEM_MOD_CRIT_MELEE_RATING_SHORT = "critR_phys",
  ITEM_MOD_CRIT_RANGED_RATING_SHORT = "critR_phys", ITEM_MOD_CRIT_SPELL_RATING_SHORT = "critR_spell",
  ITEM_MOD_HIT_RATING_SHORT = "hitR", ITEM_MOD_HIT_MELEE_RATING_SHORT = "hitR_phys",
  ITEM_MOD_HIT_RANGED_RATING_SHORT = "hitR_phys", ITEM_MOD_HIT_SPELL_RATING_SHORT = "hitR_spell",
}

-- Classic-style "Equip:" lines that GetItemStats doesn't report. Matched on keywords (EN + FR)
-- rather than exact sentences so small wording differences between builds don't break them.
local scanTip = CreateFrame("GameTooltip", "BrokenMetaWeightsScanTip", nil, "GameTooltipTemplate")
scanTip:SetOwner(WorldFrame, "ANCHOR_NONE")
-- ASCII-only lowercase: string.lower follows the C locale and can mangle UTF-8 bytes (É, é...).
local function lower(s) return (s:gsub("[A-Z]", string.lower)) end
local EQUIP = lower(ITEM_SPELL_TRIGGER_ONEQUIP or "Equip:")

local function has(line, ...)
  for i = 1, select("#", ...) do
    if line:find(select(i, ...), 1, true) then return true end
  end
end

local function parseEquipLine(line, out)
  local isSpell = has(line, "spell", "sort")
  local pct = tonumber(line:match("(%d+)%s*%%"))
  local num = tonumber(line:match("(%d+)"))
  if not num then return end
  if has(line, "critical", "critique") then
    if pct then out[isSpell and "critP_spell" or "critP_phys"] = (out[isSpell and "critP_spell" or "critP_phys"] or 0) + pct
    else out[isSpell and "critR_spell" or "critR"] = (out[isSpell and "critR_spell" or "critR"] or 0) + num end
  elseif has(line, "chance to hit", "chances de toucher", "hit rating", "score de toucher") then
    if pct then out[isSpell and "hitP_spell" or "hitP_phys"] = (out[isSpell and "hitP_spell" or "hitP_phys"] or 0) + pct
    else out[isSpell and "hitR_spell" or "hitR"] = (out[isSpell and "hitR_spell" or "hitR"] or 0) + num end
  elseif has(line, "ranged attack power", "puissance d'attaque à distance") then
    out.rap = (out.rap or 0) + num
  elseif has(line, "attack power", "puissance d'attaque") then
    out.ap = (out.ap or 0) + num
  elseif has(line, "damage and healing", "dégâts et les soins", "dégâts et soins")
      and has(line, "magical", "magiques") then
    out.sp = (out.sp or 0) + num
  end
end

local function itemStats(link)
  local out = {}
  local ok, stats = pcall(GetStats, link)
  if ok and stats then
    for k, v in pairs(stats) do
      local key = STAT_KEYS[k]
      if key then out[key] = (out[key] or 0) + v end
    end
  end
  -- Only fall back to text for stat families GetItemStats said nothing about (no double count).
  local fromApi = {
    ap = out.ap or out.rap, sp = out.sp,
    crit = out.critR or out.critR_phys or out.critR_spell,
    hit = out.hitR or out.hitR_phys or out.hitR_spell,
  }
  scanTip:ClearLines()
  scanTip:SetHyperlink(link)
  local text = {}
  for i = 2, scanTip:NumLines() do
    local fs = _G["BrokenMetaWeightsScanTipTextLeft" .. i]
    local line = fs and fs:GetText()
    if line then
      line = lower(line)
      if line:find(EQUIP, 1, true) == 1 then parseEquipLine(line, text) end
    end
  end
  for k, v in pairs(text) do
    local family = (k:match("^crit") and "crit") or (k:match("^hit") and "hit") or (k == "rap" and "ap") or k
    if not fromApi[family] then out[k] = (out[k] or 0) + v end
  end
  return out
end

-- Simulated DPS this item's stats are worth for the current spec (linear stat weights).
local function score(link)
  if not currentSpec or not link then return nil end
  local cached = scoreCache[link]
  if cached then return cached end
  local s = ns.WEIGHTS[currentSpec]
  local w = s.w
  local st = itemStats(link)
  local own = s.caster and "spell" or "phys"
  local critR = (st.critR or 0) + (st["critR_" .. own] or 0)
  local hitR = (st.hitR or 0) + (st["hitR_" .. own] or 0)
  local critP = (st["critP_" .. own] or 0) + critR / ratingPerPct.crit
  local hitP = (st["hitP_" .. own] or 0) + hitR / ratingPerPct.hit
  local ap = (st.ap or 0) + (s.ranged and (st.rap or 0) or 0)
  local total = (st.str or 0) * w.str + (st.agi or 0) * w.agi + (st.int or 0) * w.int
    + ap * w.ap + (st.sp or 0) * w.sp + critP * w.crit + hitP * w.hit
  scoreCache[link] = total
  return total
end

---------------------------------------------------------------------------------------------
-- Comparison with equipped gear
---------------------------------------------------------------------------------------------
local SLOTS = {
  INVTYPE_HEAD = { 1 }, INVTYPE_NECK = { 2 }, INVTYPE_SHOULDER = { 3 }, INVTYPE_CHEST = { 5 },
  INVTYPE_ROBE = { 5 }, INVTYPE_WAIST = { 6 }, INVTYPE_LEGS = { 7 }, INVTYPE_FEET = { 8 },
  INVTYPE_WRIST = { 9 }, INVTYPE_HAND = { 10 }, INVTYPE_FINGER = { 11, 12 },
  INVTYPE_TRINKET = { 13, 14 }, INVTYPE_CLOAK = { 15 }, INVTYPE_WEAPON = { 16, 17 },
  INVTYPE_2HWEAPON = { 16 }, INVTYPE_WEAPONMAINHAND = { 16 }, INVTYPE_WEAPONOFFHAND = { 17 },
  INVTYPE_SHIELD = { 17 }, INVTYPE_HOLDABLE = { 17 }, INVTYPE_RANGED = { 18 },
  INVTYPE_RANGEDRIGHT = { 18 }, INVTYPE_THROWN = { 18 }, INVTYPE_RELIC = { 18 },
}

-- Returns the delta against the weakest equipped item in the matching slot(s) (an empty slot
-- counts as 0), or nil + "same" when the hovered item is the one already equipped.
local function deltaVsEquipped(link, itemScore)
  local equipLoc = select(9, GetItemInfo(link))
  local slots = equipLoc and SLOTS[equipLoc]
  if not slots then return nil end
  local worst
  for _, slot in ipairs(slots) do
    local eq = GetInventoryItemLink("player", slot)
    if eq == link then return nil, true end
    local v = eq and score(eq) or 0
    if not worst or v < worst then worst = v end
  end
  return itemScore - worst
end

---------------------------------------------------------------------------------------------
-- Tooltip
---------------------------------------------------------------------------------------------
local function onTooltipItem(tt)
  if tt == scanTip or not currentSpec or not tt.GetItem then return end
  local _, link = tt:GetItem()
  local equipLoc = link and select(9, GetItemInfo(link))
  if not equipLoc or equipLoc == "" then return end
  local v = score(link)
  if not v or v <= 0 then return end
  local line = string.format("%s · %s : |cffffffff~%.2f DPS|r", L.header, specName(currentSpec), v)
  local d, same = deltaVsEquipped(link, v)
  if same then
    line = line .. "  |cff888888(" .. L.same .. ")|r"
  elseif d then
    local color = d > 0.005 and "|cff40ff40+" or (d < -0.005 and "|cffff5050" or "|cffcccccc")
    line = line .. string.format("  %s%.2f|r %s", color, d, L.vs_equipped)
  end
  tt:AddLine(line, 0.31, 0.82, 0.77)
  tt:Show()
end

if TooltipDataProcessor and Enum and Enum.TooltipDataType and Enum.TooltipDataType.Item then
  TooltipDataProcessor.AddTooltipPostCall(Enum.TooltipDataType.Item, onTooltipItem)
else
  for _, name in ipairs({ "GameTooltip", "ItemRefTooltip", "ShoppingTooltip1", "ShoppingTooltip2" }) do
    local tt = _G[name]
    if tt then tt:HookScript("OnTooltipSetItem", onTooltipItem) end
  end
end

---------------------------------------------------------------------------------------------
-- Slash commands
---------------------------------------------------------------------------------------------
local function printWeights()
  if not currentSpec then return say(L.no_spec) end
  local w = ns.WEIGHTS[currentSpec].w
  say(string.format(L.weights, specName(currentSpec)))
  local approx = ratingPerPct.crit_approx and (" (" .. L.approx .. ")") or ""
  say(string.format("  Str %.3f · Agi %.3f · Int %.3f · AP %.3f · SP %.3f", w.str, w.agi, w.int, w.ap, w.sp))
  say(string.format("  Crit 1%% %.3f (= %.1f rating) · Hit 1%% %.3f (= %.1f rating)%s",
    w.crit, ratingPerPct.crit, w.hit, ratingPerPct.hit, approx))
end

SLASH_BROKENMETAWEIGHTS1 = "/bmw"
SlashCmdList.BROKENMETAWEIGHTS = function(msg)
  local cmd, arg = (msg or ""):lower():match("^(%S*)%s*(.-)$")
  if cmd == "list" then
    for _, id in ipairs(classSpecs()) do
      say(string.format("  %s%s = %s", id == currentSpec and "> " or "", id, specName(id)))
    end
  elseif cmd == "spec" then
    if ns.WEIGHTS[arg] and ns.WEIGHTS[arg].class == playerClass then
      BrokenMetaWeightsDB.chars[charKey] = arg
      ns.ChooseSpec(arg)
      say(string.format(L.spec_set, specName(arg)))
    else
      say(string.format(L.spec_unknown, arg))
    end
  elseif cmd == "auto" then
    BrokenMetaWeightsDB.chars[charKey] = nil
    setSpec(detectSpec()); refreshRatings()
    if ns.OnDataChanged then ns.OnDataChanged() end
    say(L.spec_auto .. " " .. string.format(L.spec_set, currentSpec and specName(currentSpec) or "-"))
  elseif cmd == "weights" then
    printWeights()
  elseif cmd == "probe" then
    -- Which talent/spec APIs this client exposes (Forever mixes Classic data with the modern UI).
    for _, name in ipairs({ "GetNumTalentTabs", "GetTalentTabInfo", "GetTalentInfo", "C_ClassTalents",
        "C_Traits", "C_SpecializationInfo", "GetSpecialization", "GetCombatRatingBonusForCombatRatingValue",
        "GetCombatRatingBonus", "C_Container", "C_Item" }) do
      say(string.format("  %s: %s", name, _G[name] and type(_G[name]) or "|cffff5050nil|r"))
    end
    local _, perTab = readTalents()
    say("  points per tree: " .. (perTab and table.concat(perTab, " / ") or "nil")
      .. " -> tree " .. tostring(talentTabWithMostPoints()))
  elseif cmd == "minimap" and ns.ToggleMinimap then
    ns.ToggleMinimap()
  elseif cmd == "export" and ns.ShowExport then
    ns.ShowExport()
  elseif cmd == "" and ns.ToggleHub then
    ns.ToggleHub()
  else
    say(L.help)
  end
end

---------------------------------------------------------------------------------------------
-- Events
---------------------------------------------------------------------------------------------
local f = CreateFrame("Frame")
-- pcall: registering an event this client doesn't know raises an error on modern clients.
for _, ev in ipairs({ "PLAYER_LOGIN", "PLAYER_LEVEL_UP", "PLAYER_EQUIPMENT_CHANGED", "BAG_UPDATE_DELAYED",
    "CHARACTER_POINTS_CHANGED", "TRAIT_CONFIG_UPDATED", "PLAYER_TALENT_UPDATE" }) do
  pcall(f.RegisterEvent, f, ev)
end
f:SetScript("OnEvent", function(_, event)
  if event == "BAG_UPDATE_DELAYED" then
    -- only the hub cares about bag contents
  elseif event == "PLAYER_LOGIN" then
    BrokenMetaWeightsDB = BrokenMetaWeightsDB or {}
    BrokenMetaWeightsDB.chars = BrokenMetaWeightsDB.chars or {}
    setSpec(detectSpec())
    refreshRatings()
  elseif event == "PLAYER_EQUIPMENT_CHANGED" then
    refreshRatings() -- equipped rating changes can refine the rating->% measurement
  elseif not BrokenMetaWeightsDB.chars[charKey] then
    setSpec(detectSpec())
    refreshRatings()
  else
    refreshRatings()
  end
  if ns.OnDataChanged then ns.OnDataChanged() end
end)

---------------------------------------------------------------------------------------------
-- Shared with Hub.lua
---------------------------------------------------------------------------------------------
ns.L, ns.IS_FR, ns.say = L, IS_FR, say
ns.SLOTS = SLOTS
ns.score, ns.deltaVsEquipped, ns.itemStats = score, deltaVsEquipped, itemStats
ns.classSpecs, ns.specName = classSpecs, specName
ns.GetItemInfo = GetItemInfo
function ns.GetSpec() return currentSpec end
function ns.GetRatingPerPct() return ratingPerPct end
function ns.PlayerClass() return playerClass end
function ns.ChooseSpec(id)
  BrokenMetaWeightsDB.chars[charKey] = id
  setSpec(id); refreshRatings()
  if ns.OnDataChanged then ns.OnDataChanged() end
end
