"""Rotation section of the specialization guides (level 60): our simulated priority list (wow_rank_texts.ROTATION) set against what the Icy Veins
Forever guides recommend. The Icy Veins guides are written for the level-30 beta and for leveling, so the comparison keeps what both agree on,
adopts what the simulator confirmed at level 60 and says where the two differ and why. Icy Veins' advice is paraphrased, never copied.
Keys are "class/spec" as in data/wow_guides/content.json. HEALER_MAIN: healing specs are not simulated, their list is Icy Veins' healing rotation."""

# What the Icy Veins guide recommends (level 30 beta, paraphrased)
IV = {
    "warrior/fury": {
        "fr": ["Battle Shout toujours actif, Bloodrage entre les combats, Charge pour ouvrir, Demoralizing Shout sur la cible.", "Victory Rush après une mort, Rend tôt, Overpower après une esquive, Sunder Armor une ou deux fois.", "Execute déconseillé pendant la montée en niveau."],
        "en": ["Keep Battle Shout up, Bloodrage between pulls, Charge to open, Demoralizing Shout on the target.", "Victory Rush after a kill, Rend early, Overpower after a dodge, Sunder Armor once or twice.", "Execute is not recommended while leveling."]},
    "warrior/arms": {
        "fr": ["Battle Shout, Bloodrage entre les combats, Charge pour ouvrir, Demoralizing Shout.", "Rend tôt, Overpower après une esquive ou un déclenchement de Bloodthrill, Slam juste après un coup automatique, Sunder Armor une ou deux fois.", "Spearing Strike comme dépense de rage (dégâts triplés contre les Géants et les Dragonnets), Execute déconseillé en montée de niveau."],
        "en": ["Battle Shout, Bloodrage between pulls, Charge to open, Demoralizing Shout.", "Rend early, Overpower after a dodge or a Bloodthrill proc, Slam right after an auto-attack, Sunder Armor once or twice.", "Spearing Strike as a rage dump (triple damage against Giants and Dragonkin), Execute not recommended while leveling."]},
    "warrior/protection": {
        "fr": ["La rage vient des attaques automatiques, des dégâts subis et des techniques ; Bloodrage pour la maintenir.", "Heroic Strike transforme un coup blanc en coup spécial qui ne génère pas de rage : c'est surtout une dépense de fin de jeu quand il y a trop de rage."],
        "en": ["Rage comes from auto-attacks, damage taken and abilities; Bloodrage keeps it up.", "Heroic Strike turns a white hit into a special attack that generates no rage: it is mostly an end-game dump when you have too much rage."]},
    "rogue/combat": {
        "fr": ["Ouvrir par Ambush depuis le camouflage, Backstab si vous êtes derrière la cible, sinon Sinister Strike.", "Eviscerate ou Slice and Dice à 5 points de combo ; Instant Poison sur les deux armes."],
        "en": ["Open with Ambush from stealth, Backstab if you are behind the target, otherwise Sinister Strike.", "Eviscerate or Slice and Dice at 5 combo points; Instant Poison on both weapons."]},
    "rogue/assassination": {
        "fr": ["Camouflage puis Ambush ; Mutilate pour construire les points de combo.", "Eviscerate ou Slice and Dice à 5 points ; Instant Poison sur les deux armes."],
        "en": ["Stealth then Ambush; Mutilate to build combo points.", "Eviscerate or Slice and Dice at 5 points; Instant Poison on both weapons."]},
    "rogue/subtlety": {
        "fr": ["Hemorrhage comme générateur de points de combo en permanence (pas besoin d'être derrière la cible) ; Ambush depuis le camouflage.", "Eviscerate ou Slice and Dice à 5 points ; Rupture sur les cibles qui vivent toute la durée, meilleur que Slice and Dice au niveau 30."],
        "en": ["Hemorrhage as the combo builder at all times (no need to be behind the target); Ambush from stealth.", "Eviscerate or Slice and Dice at 5 points; Rupture on targets that live the full duration, better than Slice and Dice at level 30."]},
    "mage/fire": {
        "fr": ["Ouvrir par Pyroblast, Fireball comme sort de base (Frostfire Bolt le remplace à partir du niveau 40), Fire Blast pour finir.", "Zone : Flamestrike, Blast Wave, Arcane Explosion."],
        "en": ["Open with Pyroblast, Fireball as the filler (Frostfire Bolt replaces it from level 40), Fire Blast to finish.", "Area: Flamestrike, Blast Wave, Arcane Explosion."]},
    "mage/frost": {
        "fr": ["Frostbolt en continu ; annuler l'incantation pour un Ice Lance quand Fingers of Frost se déclenche.", "Mettre un Ice Lance en file après Frostbite, et continuer tant que la cible est gelée."],
        "en": ["Frostbolt continuously; cancel the cast for an Ice Lance when Fingers of Frost procs.", "Queue an Ice Lance after Frostbite, and keep casting it while the target is frozen."]},
    "mage/arcane": {
        "fr": ["Arcane Blast comme sort principal : 1 à 2 lancers au début de chaque combat, Arcane Missiles quand Missile Barrage se déclenche.", "Vider les charges avec Fire Blast après 2 à 3 Arcane Blast ; Arcane Explosion contre 3 ennemis ou plus."],
        "en": ["Arcane Blast as the main filler: 1-2 casts at the start of each fight, Arcane Missiles on a Missile Barrage proc.", "Dump the stacks with Fire Blast after 2-3 Arcane Blasts; Arcane Explosion against 3+ enemies."]},
    "warlock/affliction": {
        "fr": ["Démon envoyé en premier, une malédiction (Recklessness ou Elements) sur les boss.", "Immolate (lancé avant le combat), Bane of Agony si la cible vit assez longtemps, Siphon Life (cible de 20 s ou plus), Corruption (instantanée), Drain Life quand vous êtes blessé.", "Shadow Bolt quand Nightfall le rend instantané, baguette pour finir, Life Tap pour la mana."],
        "en": ["Send the demon in first, a curse (Recklessness or Elements) on bosses.", "Immolate (pre-cast), Bane of Agony if the target lives long enough, Siphon Life (20 s or more), Corruption (instant), Drain Life when hurt.", "Shadow Bolt when Nightfall makes it instant, wand to finish, Life Tap for mana."]},
    "warlock/destruction": {
        "fr": ["Démon envoyé en premier, malédiction sur les boss ; un Shadow Bolt avant le combat puis Immolate (les deux arrivent ensemble).", "Immolate est le seul effet sur la durée à gérer ; Shadow Bolt comme sort de base (Searing Pain pour un lancer plus rapide).", "Conflagrate vers la fin d'Immolate, Shadowburn pour finir, Life Tap pour la mana."],
        "en": ["Send the demon in first, a curse on bosses; pre-cast one Shadow Bolt then Immolate (the two land together).", "Immolate is the only damage-over-time to manage; Shadow Bolt as the filler (Searing Pain for a faster cast).", "Conflagrate near the end of Immolate, Shadowburn to finish, Life Tap for mana."]},
    "warlock/demonology": {
        "fr": ["Le démon attaque en permanence (Demonic Energies le soigne), Soul Link actif.", "Immolate, Bane of Agony, Corruption ; Drain Life (qui soigne aussi le démon), baguette pour finir."],
        "en": ["The demon attacks throughout (Demonic Energies heals it), Soul Link active.", "Immolate, Bane of Agony, Corruption; Drain Life (it heals the demon too), wand to finish."]},
    "hunter/beast-mastery": {
        "fr": ["Hunter's Mark et Serpent Sting avant tout, familier envoyé en premier ; Summon Hawk dès qu'il est prêt pour garder 2 faucons.", "Aimed Shot dès qu'il est prêt, Auto Shot entre deux ; Arcane Shot si la mana est pleine ; Multi-Shot à la place d'Aimed Shot contre plusieurs ennemis."],
        "en": ["Hunter's Mark and Serpent Sting first, pet sent in first; Summon Hawk on cooldown to keep 2 hawks out.", "Aimed Shot on cooldown, Auto Shot in between; Arcane Shot if mana is capped; Multi-Shot instead of Aimed Shot against several enemies."]},
    "hunter/marksmanship": {
        "fr": ["Hunter's Mark et Serpent Sting avant tout, familier envoyé en premier.", "Aimed Shot dès qu'il est prêt, Auto Shot entre deux ; Arcane Shot si la mana est pleine."],
        "en": ["Hunter's Mark and Serpent Sting first, pet sent in first.", "Aimed Shot on cooldown, Auto Shot in between; Arcane Shot if mana is capped."]},
    "hunter/survival": {
        "fr": ["À distance : Hunter's Mark, Serpent Sting, Aimed Shot dès qu'il est prêt, Auto Shot, Arcane Shot en surplus de mana.", "Au corps à corps : Serpent Sting, Raptor Strike dès qu'il est prêt, Mongoose Bite dès qu'il est disponible, Strider Kick dès qu'il est prêt. Au niveau 30, le corps à corps commence à dépasser la distance sur une cible pour un build Survie complet."],
        "en": ["Ranged: Hunter's Mark, Serpent Sting, Aimed Shot on cooldown, Auto Shot, Arcane Shot with spare mana.", "Melee: Serpent Sting, Raptor Strike on cooldown, Mongoose Bite whenever available, Strider Kick on cooldown. At level 30, melee starts to pass ranged on one target for a full Survival build."]},
    "priest/shadow": {
        "fr": ["Power Word: Shield et Inner Fire, Mind Blast pour engager, puis Devouring Plague, Shadow Word: Pain et Mind Flay (attention à la mana).", "Finir à la baguette pour économiser la mana ; Smite à la place de Mind Flay avant de l'apprendre."],
        "en": ["Power Word: Shield and Inner Fire, Mind Blast to pull, then Devouring Plague, Shadow Word: Pain and Mind Flay (watch your mana).", "Finish with the wand to save mana; Smite instead of Mind Flay before it is learned."]},
    "shaman/elemental": {
        "fr": ["Poser tous les totems avant le combat, Searing Totem en dernier (durée plus courte).", "Lightning Bolt pour engager, Flame Shock puis le rafraîchir, Lightning Bolt jusqu'à la mort de la cible.", "Fire Nova à chaque fois qu'il est prêt, seulement contre 3 ennemis ou plus."],
        "en": ["Put every totem down before the pull, Searing Totem last (shorter duration).", "Lightning Bolt to pull, Flame Shock then refresh it, Lightning Bolt until the target dies.", "Fire Nova on cooldown, only against 3 or more enemies."]},
    "shaman/enhancement": {
        "fr": ["Windfury Weapon en permanence, Mana Spring Totem pour la mana.", "Stormstrike dès qu'il est prêt, puis Earth Shock (Flame Shock en alternance en groupe, Frost Shock si la menace pose problème).", "Fire Nova avec un totem de feu actif si la mana le permet ; Maelstrom Weapon demande ses 5 points pour s'intégrer à la rotation."],
        "en": ["Windfury Weapon at all times, Mana Spring Totem for mana.", "Stormstrike on cooldown, then Earth Shock (Flame Shock alternating in groups, Frost Shock if threat is a problem).", "Fire Nova with an active Fire Totem if mana allows; Maelstrom Weapon needs all 5 points to fit the rotation."]},
    "druid/balance": {
        "fr": ["Moonfire toujours actif, puis Wrath ; Insect Swarm après Moonfire à partir du niveau 25.", "Hurricane (zone) n'est pas disponible dans la bêta."],
        "en": ["Keep Moonfire up, then Wrath; Insect Swarm after Moonfire from level 25.", "Hurricane (area) is not available in the beta."]},
    "druid/feral-combat": {
        "fr": ["Chat : Shred pour construire les points de combo (Claw si vous ne pouvez pas être derrière), Rip quand la cible vit assez longtemps, Shifting Power dès qu'il est prêt ; Rake est secondaire.", "Ours : Primal Bite est la dépense de rage principale, Swipe contre plusieurs ennemis, Maul pour brûler l'excès de rage ; Enrage dès qu'il est prêt."],
        "en": ["Cat: Shred to build combo points (Claw if you cannot get behind), Rip when the target lives long enough, Shifting Power on cooldown; Rake is secondary.", "Bear: Primal Bite is the main rage spender, Swipe against several enemies, Maul to burn extra rage; Enrage on cooldown."]},
    "paladin/retribution": {
        "fr": ["Toujours un Sceau actif : Seal of Righteousness avec beaucoup de puissance des sorts et une arme rapide, Seal of Command avec une arme lente.", "Judgement et Holy Strike dès qu'ils sont prêts ; Seal of the Crusader avant un Judgement si la cible vit longtemps ; Holy Shock en priorité pour le « Shockadin » ; Exorcism seulement contre les morts-vivants et les démons."],
        "en": ["Always keep a Seal up: Seal of Righteousness with lots of spell power and a fast weapon, Seal of Command with a slow weapon.", "Judgement and Holy Strike on cooldown; Seal of the Crusader before a Judgement if the target lives long; Holy Shock on cooldown for the Shockadin build; Exorcism only against undead and demons."]},
    "paladin/protection": {
        "fr": ["Righteous Fury en permanence ; Seal of Fury actif (il permet aussi à Judgement de provoquer).", "Consecration tant que la mana le permet (menace de zone), Judgement pour la menace, Holy Strike dès qu'il est prêt ; Exorcism seulement contre les morts-vivants et les démons."],
        "en": ["Righteous Fury at all times; Seal of Fury up (it also lets Judgement taunt).", "Consecration as long as mana allows (area threat), Judgement for threat, Holy Strike on cooldown; Exorcism only against undead and demons."]},
}

# Our verdict: what both agree on, what the level-60 simulation changed, where they differ
VERDICT = {
    "warrior/fury": {
        "fr": "Sur un boss de niveau 60, ce sont Bloodthirst, Whirlwind, Heroic Strike et Execute (sous 20 % de vie) qui font les dégâts. Victory Rush (après une mort) et Demoralizing Shout ne servent pas contre un boss. Rend ne rapporte que pour les Armes avec Bloodthrill (mesuré).",
        "en": "Against a level-60 boss, Bloodthirst, Whirlwind, Heroic Strike and Execute (under 20% health) do the damage. Victory Rush (after a kill) and Demoralizing Shout do not apply to a boss. Rend only pays off for Arms with Bloodthrill (measured)."},
    "warrior/arms": {
        "fr": "D'accord : Rend pour nourrir Bloodthrill, Overpower, Slam après le coup (testés : Rend + Bloodthrill ajoutent 34 DPS, Rend seul fait perdre du DPS). Différent contre un boss : Execute est utile au niveau 60 sous 20 % de vie, et Spearing Strike (40 % des dégâts d'arme) reste de côté.",
        "en": "Agreed: Rend to feed Bloodthrill, Overpower, Slam after the swing (tested: Rend + Bloodthrill add 34 DPS, Rend alone loses DPS). Different against a boss: Execute is worth it at level 60 under 20% health, and Spearing Strike (40% weapon damage) stays out."},
    "warrior/protection": {
        "fr": "D'accord : Heroic Strike comme dépense de rage. Le simulateur le lance avant Sunder Armor, ce qui donne +13 % de menace par seconde par rapport à l'ordre inverse (mesuré), puis Shield Slam et Revenge sur leurs conditions.",
        "en": "Agreed: Heroic Strike as the rage dump. The simulator casts it before Sunder Armor, which gives +13% threat per second over the reverse order (measured), then Shield Slam and Revenge on their conditions."},
    "rogue/combat": {
        "fr": "D'accord : Sinister Strike, Slice and Dice, Eviscerate à 5 points. Le simulateur ajoute Adrenaline Rush et Blade Flurry dès qu'ils sont prêts. Poisons : Instant en main droite et Deadly en main gauche, valeurs de Classic (hypothèse).",
        "en": "Agreed: Sinister Strike, Slice and Dice, Eviscerate at 5 points. The simulator adds Adrenaline Rush and Blade Flurry on cooldown. Poisons: Instant on the main hand and Deadly on the off hand, Classic values (assumed)."},
    "rogue/assassination": {
        "fr": "D'accord : Mutilate (avec deux dagues), Slice and Dice, Eviscerate à 5 points. Les dagues sont rares dans le butin connu : l'optimiseur retient souvent une épée et une dague, et le simulateur joue alors Sinister Strike.",
        "en": "Agreed: Mutilate (with two daggers), Slice and Dice, Eviscerate at 5 points. Daggers are scarce in the known loot: the optimizer often keeps a sword and a dagger, and the simulator then plays Sinister Strike."},
    "rogue/subtlety": {
        "fr": "D'accord : Hemorrhage en permanence, Slice and Dice, Eviscerate. Rupture n'est pas encore simulée (ses chiffres dans le client sont faibles : 35 de base, +4,7 par point de combo, toutes les 2 secondes) : à confirmer en jeu.",
        "en": "Agreed: Hemorrhage at all times, Slice and Dice, Eviscerate. Rupture is not simulated yet (its client numbers are small: 35 base, +4.7 per combo point, every 2 seconds): to confirm in game."},
    "mage/fire": {
        "fr": "D'accord : Pyroblast (avec Heating Up), Fire Blast, Frostfire Bolt comme sort de base (il remplace bien Fireball), plus Scorch pour Improved Scorch et Combustion. Les sorts de zone ne comptent pas contre une seule cible.",
        "en": "Agreed: Pyroblast (with Heating Up), Fire Blast, Frostfire Bolt as the filler (it does replace Fireball), plus Scorch for Improved Scorch and Combustion. Area spells do not count against one target."},
    "mage/frost": {
        "fr": "D'accord : Frostbolt en continu et Ice Lance sur cible gelée. Frost Nova est un outil de contrôle, pas simulé.",
        "en": "Agreed: Frostbolt continuously and Ice Lance on a frozen target. Frost Nova is a control tool, not simulated."},
    "mage/arcane": {
        "fr": "Différent, et mesuré : sur un combat de boss de 3 minutes, les charges d'Arcane Blast coûtent trop de mana (+175 % par charge). Une rotation Arcane Blast puis Missiles tombe à 308 DPS, contre 452 pour Arcane Missiles + Arcane Power. Le conseil d'Icy Veins vaut pour la montée en niveau (combats courts, boisson libre). Les déclenchements de Missile Barrage ne sont pas simulés.",
        "en": "Different, and measured: over a 3-minute boss fight Arcane Blast stacks cost too much mana (+175% per stack). A rotation of Arcane Blast then Missiles drops to 308 DPS, against 452 for Arcane Missiles + Arcane Power. Icy Veins' advice fits leveling (short fights, free drinking). Missile Barrage procs are not simulated."},
    "warlock/affliction": {
        "fr": "D'accord, et adopté après mesure : Bane of Agony plutôt que Bane of Doom (+16 DPS sur un combat de 3 minutes) et Immolate dans la rotation (+3 DPS). Wrack est propre à Forever. Les malédictions de raid (Elements, Recklessness) sont comptées comme debuffs.",
        "en": "Agreed, and adopted after measuring: Bane of Agony instead of Bane of Doom (+16 DPS over a 3-minute fight) and Immolate in the rotation (+3 DPS). Wrack is Forever-specific. Raid curses (Elements, Recklessness) are counted as debuffs."},
    "warlock/destruction": {
        "fr": "D'accord : Immolate en premier, Conflagrate et Shadowburn dès qu'ils sont prêts, Incinerate comme sort de base au niveau 60. Ajouté après mesure : Bane of Agony (+6 DPS par rapport à Doom). Searing Pain donne beaucoup de menace pour peu de dégâts.",
        "en": "Agreed: Immolate first, Conflagrate and Shadowburn on cooldown, Incinerate as the filler at level 60. Added after measuring: Bane of Agony (+6 DPS over Doom). Searing Pain gives a lot of threat for little damage."},
    "warlock/demonology": {
        "fr": "D'accord : le diablotin reste en jeu avec Demonic Knowledge et Unholy Power (le sacrifier fait perdre environ 80 DPS dans le simulateur), Immolate, Corruption et Bane of Agony (+12 DPS par rapport à Doom, mesuré).",
        "en": "Agreed: the Imp stays out with Demonic Knowledge and Unholy Power (sacrificing it loses about 80 DPS in the simulator), Immolate, Corruption and Bane of Agony (+12 DPS over Doom, measured)."},
    "hunter/beast-mastery": {
        "fr": "D'accord, et ajouté : Hunter's Mark (+110 de puissance d'attaque à distance, valeur du client), Serpent Sting, Summon Hawk, les attaques du familier, Arcane Shot. Différent : au niveau 60 sur une cible, Multi-Shot fait environ 4 % de mieux qu'Aimed Shot (qui coûte une incantation de 2 s), donc le simulateur tire Multi-Shot.",
        "en": "Agreed, and added: Hunter's Mark (+110 ranged attack power, client value), Serpent Sting, Summon Hawk, the pet's attacks, Arcane Shot. Different: at level 60 on one target Multi-Shot does about 4% better than Aimed Shot (which costs a 2-second cast), so the simulator fires Multi-Shot."},
    "hunter/marksmanship": {
        "fr": "D'accord, et ajouté : Hunter's Mark (+110 de puissance d'attaque à distance, valeur du client), Serpent Sting, Arcane Shot. Différent : au niveau 60 sur une cible, Multi-Shot fait environ 4 % de mieux qu'Aimed Shot (incantation de 2 s) dans le simulateur, et Sniper Shot (incantation de 4 s qui coupe l'Auto Shot) fait perdre environ 4 % : le build ne le prend pas.",
        "en": "Agreed, and added: Hunter's Mark (+110 ranged attack power, client value), Serpent Sting, Arcane Shot. Different: at level 60 on one target Multi-Shot does about 4% better than Aimed Shot (2-second cast) in the simulator, and Sniper Shot (a 4-second cast that stops Auto Shot) costs about 4%: the build does not take it."},
    "hunter/survival": {
        "fr": "D'accord sur les deux variantes (Hunter's Mark ajouté à la version à distance). Différent : Icy Veins voit le corps à corps dépasser la distance au niveau 30 ; avec l'équipement connu au niveau 60, le simulateur garde la distance devant (environ 493 DPS contre 422), et Multi-Shot y fait 6 % de mieux qu'Aimed Shot.",
        "en": "Agreed on both variants (Hunter's Mark added to the ranged one). Different: Icy Veins sees melee passing ranged at level 30; with the known level-60 gear the simulator keeps ranged ahead (about 493 DPS against 422), and Multi-Shot does 6% better than Aimed Shot there."},
    "priest/shadow": {
        "fr": "D'accord : Mind Blast, Devouring Plague, Shadow Word: Pain, Mind Flay comme sort de base, plus Shadow Word: Death. Finir à la baguette est une habitude de montée en niveau, pas une partie de la rotation contre un boss.",
        "en": "Agreed: Mind Blast, Devouring Plague, Shadow Word: Pain, Mind Flay as the filler, plus Shadow Word: Death. Finishing with the wand is a leveling habit, not part of the rotation against a boss."},
    "shaman/elemental": {
        "fr": "D'accord : Searing Totem en ouverture, Flame Shock entretenu, Lightning Bolt comme sort de base. Le simulateur ajoute Lava Burst (+20 % sous Flame Shock) et Lightning Overload. Fire Nova, Chain Lightning et Earth Shock sont des outils de zone ou trop chers : sur une cible ils coûtent plus de mana qu'ils ne rapportent (mesuré : -43 à -65 DPS). Le vrai plafond de l'Élémentaire est la mana : sans potion ni gemme il perd 30 % de ses dégâts. Talents corrigés après mesure : Mindfulness (50 % de la régénération continue en lançant) et Totemic Focus, de l'arbre Restauration, remplacent des points sans effet (Mental Dexterity, Ghost Wolf...) et valent +40 DPS ; Tidal Focus (+2 % de toucher) ajoute encore 9 DPS (hypothèse : on suppose qu'il s'applique aux sorts offensifs).",
        "en": "Agreed: Searing Totem at the start, Flame Shock kept up, Lightning Bolt as the filler. The simulator adds Lava Burst (+20% under Flame Shock) and Lightning Overload. Fire Nova, Chain Lightning and Earth Shock are area tools or too expensive: on one target they cost more mana than they return (measured: -43 to -65 DPS). The Elemental's real ceiling is mana: without potion and gem it loses 30% of its damage. Talents corrected after measuring: Mindfulness (50% of the regeneration continues while casting) and Totemic Focus, from the Restoration tree, replace points with no effect (Mental Dexterity, Ghost Wolf...) and are worth +40 DPS; Tidal Focus (+2% hit) adds 9 more DPS (assumption: it applies to offensive spells)."},
    "shaman/enhancement": {
        "fr": "D'accord : Windfury Weapon, Mana Spring Totem, Stormstrike dès qu'il est prêt, les chocs dans leur créneau, Maelstrom Weapon à 5 rangs. Corrigé après mesure : le +20 % de Stormstrike vaut plus sur un Lightning Bolt que sur Earth Shock (+12 DPS) ; Frost Shock fait comme Earth Shock ; Fire Nova ne rapporte rien sur une cible (outil de zone). Talents : les 3 points d'Elemental Devastation (+9 % de critique en mêlée pendant 10 s après un critique de sort) rapportent 11 DPS de plus que les mêmes points dans Call of Flame (mesuré), grâce aux attaques automatiques et à Windfury.",
        "en": "Agreed: Windfury Weapon, Mana Spring Totem, Stormstrike on cooldown, the shocks in their slot, Maelstrom Weapon at 5 ranks. Corrected after measuring: Stormstrike's +20% is worth more on a Lightning Bolt than on Earth Shock (+12 DPS); Frost Shock does the same as Earth Shock; Fire Nova adds nothing on one target (area tool). Talents: the 3 points in Elemental Devastation (+9% melee crit for 10 s after a spell crit) are worth 11 more DPS than the same points in Call of Flame (measured), through the auto-attacks and Windfury."},
    "druid/balance": {
        "fr": "D'accord sur Moonfire et Insect Swarm. Au niveau 60, le simulateur lance surtout Starfire (environ 210 DPS contre 56 pour Wrath, voir la page du classement), avec Wrath en complément.",
        "en": "Agreed on Moonfire and Insect Swarm. At level 60 the simulator mostly casts Starfire (about 210 DPS against 56 for Wrath, see the ranking page), with Wrath as a complement."},
    "druid/feral-combat": {
        "fr": "D'accord sur les deux formes. Ajouté après mesure : Primal Bite dans la rotation de l'ours (+9 % de menace par seconde, sans compter sa « haute menace » que le client ne chiffre pas). Chat : le simulateur entretient aussi Savage Roar et utilise Tiger's Fury et Berserk.",
        "en": "Agreed on both forms. Added after measuring: Primal Bite in the bear rotation (+9% threat per second, not counting its \"high threat\", which the client does not quantify). Cat: the simulator also keeps Savage Roar up and uses Tiger's Fury and Berserk."},
    "paladin/retribution": {
        "fr": "D'accord : Seal of Command (arme à deux mains), Judgement et Holy Strike dès qu'ils sont prêts. Exorcism reste de côté contre un boss (morts-vivants et démons seulement). Pas simulés : le changement de Sceau pour Seal of the Crusader et le bonus de Hammer of Justice.",
        "en": "Agreed: Seal of Command (two-hand weapon), Judgement and Holy Strike on cooldown. Exorcism stays out against a boss (undead and demons only). Not simulated: the Seal of the Crusader swap and the Hammer of Justice bonus."},
    "paladin/protection": {
        "fr": "D'accord : Righteous Fury, Judgement, Holy Strike, plus Holy Shield dans le simulateur. Différent : Consecration est un outil de zone ; sur un boss, ses dégâts dans le client sont faibles (16 sur 8 s à son premier rang) pour 565 de mana, donc il reste de côté. Les chiffres de Seal of Fury ne sont pas encore dans nos données.",
        "en": "Agreed: Righteous Fury, Judgement, Holy Strike, plus Holy Shield in the simulator. Different: Consecration is an area tool; on a boss its damage in the client is small (16 over 8 s at its first rank) for 565 mana, so it stays out. Seal of Fury's numbers are not in our data yet."},
}

# Healing specs (not simulated): Icy Veins' healing advice (level 30, paraphrased) and our priority, built from the client's spell numbers
# (healing per mana and per second at 350 healing power, no talents: see _healing_table in build_site.py)
IV.update({
    "shaman/restoration": {
        "fr": ["Poser tous les totems avant le combat, Searing Totem en dernier.", "Healing Wave sur les blessés, en rang réduit quand les dégâts ne justifient pas le rang maximum.", "Fire Nova contre un groupe, ou Lightning Bolt sur une cible, quand aucun soin n'est urgent.", "Garder les totems de bonus en place : c'est votre meilleure contribution aux dégâts du groupe."],
        "en": ["Put every totem down before the pull, Searing Totem last.", "Healing Wave on injured targets, downranked when the damage does not justify the top rank.", "Fire Nova against a group, or Lightning Bolt on one target, when no heal is urgent.", "Keep the buff totems up: it is your best contribution to the party's damage."]},
    "druid/restoration": {
        "fr": ["Rejuvenation sur le tank et sur ceux qui subissent peu de dégâts, Healing Touch pour compléter.", "Swiftmend une seconde après un Rejuvenation quand une cible tombe bas.", "Thorns sur le tank avant le début ; Wrath ou Moonfire sur les ennemis quand il reste du temps."],
        "en": ["Rejuvenation on the tank and anyone taking light damage, Healing Touch to top up.", "Swiftmend one second after a Rejuvenation when a target drops low.", "Thorns on the tank before the run; Wrath or Moonfire on enemies when you have spare time."]},
    "paladin/holy": {
        "fr": ["Flash of Light comme soin principal (peu cher, rapide).", "Holy Light pour les gros soins quand la mana le permet ; Holy Shock instantané en urgence ; Lay on Hands en dernier recours.", "Blessing of Might sur le groupe et Devotion ou Retribution Aura en permanence ; Seal of Light pour soigner davantage."],
        "en": ["Flash of Light as the main heal (cheap, fast).", "Holy Light for big heals when mana allows; instant Holy Shock in emergencies; Lay on Hands as a last resort.", "Blessing of Might on the party and Devotion or Retribution Aura at all times; Seal of Light for extra healing."]},
    "priest/holy": {
        "fr": ["Power Word: Shield pour gagner du temps ; Heal pour un soin moyen ; Renew contre les dégâts légers.", "Flash Heal seulement en urgence (coûteux) ; Prayer of Healing quand le groupe est blessé.", "Holy Nova quand Searing Light se déclenche et que personne n'est en danger ; dissiper quand ça vaut la mana."],
        "en": ["Power Word: Shield to buy time; Heal for a moderate heal; Renew against chip damage.", "Flash Heal only in emergencies (costly); Prayer of Healing when the party is hurt.", "Holy Nova when Searing Light procs and nobody is in danger; cleanse when it is worth the mana."]},
    "priest/discipline": {
        "fr": ["Power Word: Shield au besoin ou pour gagner du temps ; Heal pour un soin moyen ; Renew contre les dégâts légers.", "Flash Heal seulement en urgence (coûteux) ; Prayer of Healing quand le groupe est blessé ; dissiper quand ça vaut la mana."],
        "en": ["Power Word: Shield as needed or to buy time; Heal for a moderate heal; Renew against chip damage.", "Flash Heal only in emergencies (costly); Prayer of Healing when the party is hurt; cleanse when it is worth the mana."]},
})
HEALER_MAIN = {
    "priest/holy": {
        "fr": ["Prayer of Mending dès qu'il est prêt (recharge de 10 s) : un soin qui rebondit, pour 390 de mana.", "Renew sur le tank et sur ceux qui subissent des dégâts réguliers : c'est le soin le plus efficace (3,35 de soin par mana, instantané).", "Greater Heal comme soin principal (3,18 par mana, 753 de soin par seconde en 3 s d'incantation) ; Heal (4 s, 3,24) seulement quand rien ne presse.", "Binding Heal quand vous et un allié êtes blessés (5,2 de soin par mana sur les deux cibles).", "Flash Heal seulement pour sauver quelqu'un (2,77 par mana, mais le plus rapide).", "Prayer of Healing quand 3 alliés ou plus sont blessés (3,5 par mana sur 5 cibles, mais 1 070 de mana)."],
        "en": ["Prayer of Mending on cooldown (10 s cooldown): a bouncing heal for 390 mana.", "Renew on the tank and anyone taking steady damage: it is the most efficient heal (3.35 healing per mana, instant).", "Greater Heal as the main heal (3.18 per mana, 753 healing per second on a 3 s cast); Heal (4 s, 3.24) only when nothing is pressing.", "Binding Heal when you and an ally are both hurt (5.2 healing per mana across the two targets).", "Flash Heal only to save someone (2.77 per mana, but the fastest).", "Prayer of Healing when 3 or more allies are hurt (3.5 per mana across 5 targets, but 1,070 mana)."]},
    "priest/discipline": {
        "fr": ["Power Word: Shield sur la cible qui va être touchée (942 d'absorption pour 500 de mana : peu efficace, à utiliser pour le moment, pas pour le volume).", "Penance dès qu'il est prêt (recharge de 12 s, instantané).", "Renew sur le tank (3,35 de soin par mana) et Greater Heal comme soin principal (3,18 par mana) ; les soins critiques créent un bouclier avec Divine Aegis.", "Flash Heal seulement en urgence (2,77 par mana) ; Prayer of Mending dès qu'il est prêt.", "Inner Focus avant un gros soin, Power Infusion sur vous-même ou sur un autre soigneur."],
        "en": ["Power Word: Shield on the target about to be hit (942 absorbed for 500 mana: inefficient, use it for timing, not volume).", "Penance on cooldown (12 s cooldown, instant).", "Renew on the tank (3.35 healing per mana) and Greater Heal as the main heal (3.18 per mana); critical heals create a shield with Divine Aegis.", "Flash Heal only in emergencies (2.77 per mana); Prayer of Mending on cooldown.", "Inner Focus before a big heal, Power Infusion on yourself or another healer."]},
    "shaman/restoration": {
        "fr": ["Riptide dès qu'il est prêt (recharge de 6 s) : 4,9 de soin par mana et instantané, c'est le soin le plus efficace.", "Healing Wave comme soin principal (3,09 par mana, 638 de soin par seconde).", "Lesser Healing Wave pour rattraper un retard ou sauver quelqu'un (2,71 par mana, 687 par seconde, incantation de 1,5 s).", "Chain Heal contre des groupes seulement (1,87 par mana sur une seule cible).", "Water Shield en permanence et Mana Tide Totem pour la mana ; Nature's Swiftness pour un soin d'urgence instantané ; Healing Stream Totem posé."],
        "en": ["Riptide on cooldown (6 s cooldown): 4.9 healing per mana and instant, the most efficient heal.", "Healing Wave as the main heal (3.09 per mana, 638 healing per second).", "Lesser Healing Wave to catch up or save someone (2.71 per mana, 687 per second, 1.5 s cast).", "Chain Heal against groups only (1.87 per mana on a single target).", "Water Shield at all times and Mana Tide Totem for mana; Nature's Swiftness for an instant emergency heal; Healing Stream Totem down."]},
    "druid/restoration": {
        "fr": ["Rejuvenation sur le tank et sur ceux qui subissent peu de dégâts (3,24 de soin par mana, instantané).", "Healing Touch comme gros soin (3,19 par mana, 766 de soin par seconde en 3,5 s ; Naturalist retire 0,5 s).", "Swiftmend après un Rejuvenation ou un Regrowth quand une cible tombe bas (recharge de 15 s).", "Regrowth en urgence (2,73 par mana mais 1 200 de soin par seconde, avec des soins sur la durée).", "Wild Growth contre un groupe blessé (3,6 par mana sur 5 cibles) ; Tranquility pour les gros dégâts de zone."],
        "en": ["Rejuvenation on the tank and anyone taking light damage (3.24 healing per mana, instant).", "Healing Touch as the big heal (3.19 per mana, 766 healing per second on a 3.5 s cast; Naturalist takes 0.5 s off).", "Swiftmend after a Rejuvenation or Regrowth when a target drops low (15 s cooldown).", "Regrowth in emergencies (2.73 per mana but 1,200 healing per second, with heals over time).", "Wild Growth against an injured group (3.6 per mana across 5 targets); Tranquility for heavy area damage."]},
    "paladin/holy": {
        "fr": ["Flash of Light comme soin principal : 3,27 de soin par mana pour seulement 140 de mana, en 1,5 s.", "Holy Light pour les gros soins quand la mana le permet (2,77 par mana, 732 de soin par seconde en 2,5 s).", "Holy Shock instantané et Light's Vigil pour les urgences ; Divine Favor avant un soin important pour garantir un critique (Illumination rend alors de la mana).", "Lay on Hands en dernier recours.", "Blessing of Might sur le groupe et une aura en permanence ; Seal of Light pour soigner davantage."],
        "en": ["Flash of Light as the main heal: 3.27 healing per mana for only 140 mana, on a 1.5 s cast.", "Holy Light for big heals when mana allows (2.77 per mana, 732 healing per second on a 2.5 s cast).", "Instant Holy Shock and Light's Vigil for emergencies; Divine Favor before an important heal to guarantee a critical (Illumination then returns mana).", "Lay on Hands as a last resort.", "Blessing of Might on the party and an aura at all times; Seal of Light for extra healing."]},
}
VERDICT.update({
    "priest/holy": {
        "fr": "D'accord avec Icy Veins : Greater Heal ou Heal pour le gros du travail, Renew contre les dégâts réguliers, Flash Heal réservé aux urgences (il coûte plus de mana pour moins de soin). Les chiffres du client ajoutent l'ordre d'efficacité (Renew, Heal, Greater Heal, Flash Heal), l'intérêt de Binding Heal sur deux cibles et de Prayer of Mending, que le guide ne chiffre pas. Calcul sans simulation de combat, à 350 de puissance de soin et sans talents.",
        "en": "Agreed with Icy Veins: Greater Heal or Heal for the bulk, Renew against steady damage, Flash Heal kept for emergencies (it costs more mana for less healing). The client numbers add the efficiency order (Renew, Heal, Greater Heal, Flash Heal), the value of Binding Heal on two targets and of Prayer of Mending, which the guide does not quantify. Computed without a combat simulation, at 350 healing power and without talents."},
    "priest/discipline": {
        "fr": "D'accord avec Icy Veins sur Power Word: Shield, Heal, Renew et Flash Heal en urgence. Les chiffres montrent que Power Word: Shield est le moins efficace en mana (1,9 par mana) : il sert à gagner du temps, pas à soigner en volume. Penance et Divine Aegis viennent des talents de Discipline. Calcul sans simulation de combat, à 350 de puissance de soin et sans talents.",
        "en": "Agreed with Icy Veins on Power Word: Shield, Heal, Renew and Flash Heal in emergencies. The numbers show Power Word: Shield is the least mana-efficient (1.9 per mana): it buys time, it does not heal in volume. Penance and Divine Aegis come from the Discipline talents. Computed without a combat simulation, at 350 healing power and without talents."},
    "shaman/restoration": {
        "fr": "D'accord avec Icy Veins : totems posés avant le combat, Healing Wave comme soin de base et Chain Heal en groupe. Les chiffres ajoutent Riptide (4,9 par mana, le soin le plus efficace, que le guide niveau 30 ne pouvait pas citer : c'est un talent de dernier palier) et montrent que Chain Heal ne vaut rien sur une seule cible. Calcul sans simulation de combat, à 350 de puissance de soin et sans talents.",
        "en": "Agreed with Icy Veins: totems down before the fight, Healing Wave as the base heal and Chain Heal for groups. The numbers add Riptide (4.9 per mana, the most efficient heal, which the level-30 guide could not mention: it is a last-tier talent) and show Chain Heal is worth little on a single target. Computed without a combat simulation, at 350 healing power and without talents."},
    "druid/restoration": {
        "fr": "D'accord avec Icy Veins : Rejuvenation sur le tank et les dégâts légers, Healing Touch pour compléter, Swiftmend après un Rejuvenation. Les chiffres ajoutent Regrowth pour l'urgence (le plus de soin par seconde, mais moins efficace en mana) et Wild Growth, un talent de dernier palier, contre les groupes (3,6 par mana sur 5 cibles). Calcul sans simulation de combat, à 350 de puissance de soin et sans talents.",
        "en": "Agreed with Icy Veins: Rejuvenation on the tank and light damage, Healing Touch to top up, Swiftmend after a Rejuvenation. The numbers add Regrowth for emergencies (the most healing per second, but less mana-efficient) and Wild Growth, a last-tier talent, against groups (3.6 per mana across 5 targets). Computed without a combat simulation, at 350 healing power and without talents."},
    "paladin/holy": {
        "fr": "D'accord avec Icy Veins : Flash of Light comme soin principal, Holy Light pour les gros soins, Holy Shock en urgence et Lay on Hands en dernier recours. Les chiffres le confirment : Flash of Light est à la fois le plus efficace (3,27 par mana) et le moins cher (140 de mana). Les chiffres de Holy Shock et de Light's Vigil ne sont pas exploitables dans le client. Calcul sans simulation de combat, à 350 de puissance de soin et sans talents.",
        "en": "Agreed with Icy Veins: Flash of Light as the main heal, Holy Light for big heals, Holy Shock in emergencies and Lay on Hands as a last resort. The numbers confirm it: Flash of Light is both the most efficient (3.27 per mana) and the cheapest (140 mana). Holy Shock's and Light's Vigil's numbers are not usable in the client. Computed without a combat simulation, at 350 healing power and without talents."},
})
HEALER_NOTE = {
    "fr": "Les soins ne sont pas simulés en combat. Cette rotation est déduite des chiffres du client (soin de base, coefficient de puissance de soin, mana, temps d'incantation) à 350 de puissance de soin et sans talents : elle donne un ordre d'efficacité, pas un résultat de simulation.",
    "en": "Healing is not simulated in combat. This rotation is derived from the client numbers (base heal, healing-power coefficient, mana, cast time) at 350 healing power and without talents: it gives an efficiency order, not a simulation result.",
}
HEAL_TX = {
    "fr": {"h3": "Efficacité des sorts de soin au niveau 60", "p": "Calculée à partir des chiffres du client à 350 de puissance de soin, sans talents. « Soin par mana » compare l'efficacité en mana ; « soin par seconde » compte au moins 1,5 s par sort (le temps minimal entre deux sorts) ; les sorts de zone sont indiqués pour une cible puis pour toutes les cibles touchées.",
           "c_spell": "Sort", "c_cast": "Incantation", "c_cost": "Mana", "c_heal": "Soin par sort", "c_hpm": "Soin par mana", "c_hps": "Soin par seconde", "c_multi": "Toutes cibles", "instant": "instantané", "hot": "avec soins sur la durée", "absorb": "absorption", "special": "Sorts de talent ou sans chiffre exploitable dans le client : "},
    "en": {"h3": "Healing spell efficiency at level 60", "p": "Computed from the client numbers at 350 healing power, without talents. \"Healing per mana\" compares mana efficiency; \"healing per second\" counts at least 1.5 s per spell (the minimum time between two spells); area spells are shown for one target, then for all targets hit.",
           "c_spell": "Spell", "c_cast": "Cast", "c_cost": "Mana", "c_heal": "Healing per cast", "c_hpm": "Healing per mana", "c_hps": "Healing per second", "c_multi": "All targets", "instant": "instant", "hot": "with heals over time", "absorb": "absorb", "special": "Talent spells or spells without a usable number in the client: "},
}

TX = {
    "fr": {"h2": "Rotation niveau 60", "intro_sim": "Priorité de notre simulateur au niveau 60, comparée à ce que recommande Icy Veins. Leurs guides sont écrits pour la bêta niveau 30 et pour la montée en niveau : nous gardons ce sur quoi tout le monde s'accorde, nous adoptons ce que la simulation a confirmé au niveau 60 et nous disons où les deux diffèrent.",
           "intro_heal": "Les soins ne sont pas encore simulés : voici la rotation de soins recommandée par Icy Veins (niveau 30), reformulée.",
           "iv_h3": "Ce que recommande Icy Veins (niveau 30)", "verdict_h3": "Notre comparaison", "src_iv": "Icy Veins : guide de la spécialisation, bêta niveau 30 (reformulé)"},
    "en": {"h2": "Level 60 rotation", "intro_sim": "Our simulator's priority at level 60, set against what Icy Veins recommends. Their guides are written for the level-30 beta and for leveling: we keep what everyone agrees on, adopt what the simulation confirmed at level 60 and say where the two differ.",
           "intro_heal": "Healing is not simulated yet: this is the healing rotation Icy Veins recommends (level 30), reworded.",
           "iv_h3": "What Icy Veins recommends (level 30)", "verdict_h3": "Our comparison", "src_iv": "Icy Veins: the specialization's guide, level-30 beta (reworded)"},
}

# Level-60 gear and stat-weight sections of the guides (data: data/wow_ranking60.json, written by sim60/ranking.mjs)
G60 = {
    "fr": {
        "cons_h2": "Meilleurs consommables niveau 60", "cons_p": "Les trois meilleurs de chaque catégorie, mesurés par le simulateur sur le personnage ci-dessus. On ne porte qu'un parchemin et qu'un élixir ou flacon à la fois : chaque gain est le DPS apporté par ce consommable seul, par rapport à un emplacement vide, le reste du lot restant identique. Les gains d'une même catégorie ne s'additionnent donc pas. La ligne marquée d'un point est celle du lot simulé.", "cons_scroll": "Parchemins", "cons_elixir": "Élixirs et flacons", "cons_other": "Potions, plats et autres", "cons_chosen": "lot simulé", "col_cons": "Consommable", "col_gain": "DPS", "col_pct": "Gain", "cons_tank": "Pour les tanks, le gain est mesuré sur la menace utile.", "cons_none": "Aucun effet mesurable.", "cons_heal": "Les soins ne sont pas simulés : ces consommables sont ceux du client qui augmentent les soins, l'intelligence, l'esprit ou la mana.", "col_ench": "Enchantement bis", "ench_none": "—", "ench_note": "Enchantements jusqu'au niveau 300 de métier, valorisés par le simulateur quand ils donnent une statistique ou des dégâts d'arme fixes. Le personnage n'a pas besoin du métier : on les achète ou on se les fait poser par un enchanteur ; les renforts d'armure du Travail du cuir (torse, jambes, pieds, mains) et les lunettes de l'Ingénierie sont comptés aussi. Un renfort et un enchantement occupent le même emplacement permanent : une pièce porte l'un ou l'autre, et les jambes, qui n'ont pas d'enchantement, reçoivent le renfort ; les enchantements qui déclenchent un sort (Crusader, Fiery Weapon...) et les dégâts d'école ne sont pas simulés. Il n'existe aucun enchantement d'anneau dans les données de la bêta jusqu'au niveau 300 de métier.", "w_chart_h": "Courbes de gain par statistique", "w_chart_p": "DPS gagné quand on ajoute des points de chaque statistique par-dessus l'équipement simulé. Cliquez sur une statistique (ou sur sa ligne dans le tableau) pour mettre sa courbe en avant ; le rond marque le plafond estimé, après lequel chaque point rapporte moins de 20 % de ce qu'il rapportait au départ.", "w_chart_x": "points ajoutés (score ou valeur de la statistique)", "w_chart_y": "DPS gagné", "prof_cta": "Guide {name}", "gear_h2": "Équipement niveau 60", "gear_p": "L'équipement que notre optimiseur retient pour cette spécialisation parmi les objets connus de la bêta (donjons, rares objets de raid déjà connus et équipement fabriqué par les métiers, que l'on peut acheter ou se faire fabriquer : prix et matériaux ne sont pas pris en compte), avec les effets d'objets simulés. Aucun objet n'est choisi à la main : c'est le résultat du calcul du classement, et il changera quand de nouveaux objets seront découverts.",
        "gear_heal": "L'équipement de soin niveau 60 n'est pas encore calculé : le simulateur ne gère pas les soins. Les pages des donjons et des raids permettent de parcourir le butin par type d'objet et par statistique.",
        "col_slot": "Emplacement", "col_item": "Objet", "col_source": "Provenance",
        "w_h2": "Priorité de statistiques niveau 60", "w_p": "Mesurée par le simulateur sur le personnage ci-dessus : le DPS gagné par un point supplémentaire de chaque statistique, avec les mêmes tirages aléatoires de chaque côté. La valeur relative compare chaque statistique à un point de {main}. Critique, toucher et hâte sont comptés par point de score, comme la Force ou l'Agilité, pour être comparables ; ils tiennent compte des plafonds : un toucher au plafond ne rapporte plus rien. Une valeur proche de zéro ou négative est dans la marge d'erreur ou liée à une limite (mana, plafond).",
        "w_main_ap": "puissance d'attaque", "w_main_sp": "puissance des sorts", "w_stat": "Statistique", "w_per": "DPS gagné", "w_rel": "Valeur relative", "w_unit_pt": "par point", "w_unit_pct": "par 1 %", "w_unit_rating": "par point de score", "iv_stats_h3": "Icy Veins (niveau 30)", "w_none": "aucun effet",
        "stats": {"atkpwr": "Puissance d'attaque", "splpwr": "Puissance des sorts", "str": "Force", "agi": "Agilité", "int": "Intelligence", "spi": "Esprit", "critstrkrtng": "Critique", "hitrtng": "Toucher", "hastertng": "Hâte"},
        "note": "Les données de talents viennent du client bêta. Le build, l'équipement, les statistiques et la rotation niveau 60 viennent de notre simulateur et sont validés par des mesures de DPS ; la rotation est comparée à celle des guides Icy Veins, écrits pour la bêta niveau 30. Les soins ne sont pas simulés. Ces données évolueront avec la bêta et avec la sortie du jeu le 4 novembre 2026.",
        "w_tank": "Pour un tank, le simulateur ne chiffre pas encore les statistiques : la liste d'Icy Veins (niveau 30) ci-dessous reste la référence.",
    },
    "en": {
        "cons_h2": "Best level 60 consumables", "cons_p": "The three best of each category, measured by the simulator on the character above. Only one scroll and one elixir or flask can be worn at a time: each gain is the DPS this consumable brings alone, compared with an empty slot, the rest of the set unchanged. Gains in the same category therefore do not add up. The row marked with a dot is the one in the simulated set.", "cons_scroll": "Scrolls", "cons_elixir": "Elixirs and flasks", "cons_other": "Potions, food and others", "cons_chosen": "simulated set", "col_cons": "Consumable", "col_gain": "DPS", "col_pct": "Gain", "cons_tank": "For tanks the gain is measured on useful threat.", "cons_none": "No measurable effect.", "cons_heal": "Healing is not simulated: these are the client consumables that raise healing, intellect, spirit or mana.", "col_ench": "Best enchant", "ench_none": "—", "ench_note": "Enchantments up to skill 300, valued by the simulator when they give flat stats or flat weapon damage. The character does not need the profession: they can be bought or applied by an enchanter; Leatherworking armor kits (chest, legs, feet, hands) and Engineering scopes are counted too. A kit and an enchantment share the same permanent slot: a piece carries one or the other, and the legs, which have no enchantment, get the kit; spell-proc enchants (Crusader, Fiery Weapon...) and school damage are not simulated. The beta data has no ring enchantment up to skill 300.", "w_chart_h": "Gain curves by stat", "w_chart_p": "DPS gained when points of each stat are added on top of the simulated gear. Click a stat (or its row in the table) to bring its curve forward; the ring marks the estimated cap, past which every point is worth less than 20% of what it gave at the start.", "w_chart_x": "points added (rating or stat value)", "w_chart_y": "DPS gained", "prof_cta": "{name} guide", "gear_h2": "Level 60 gear", "gear_p": "The gear our optimizer picks for this specialization among the items known from the beta (dungeons, the few raid items already known and crafted gear, which can be bought or made for you: prices and materials are not taken into account), with item effects simulated. Nothing is hand-picked: it is the result of the ranking's computation, and it will change as new items are discovered.",
        "gear_heal": "Level-60 healing gear is not computed yet: the simulator does not model healing. The dungeon and raid pages let you browse loot by item type and stat.",
        "col_slot": "Slot", "col_item": "Item", "col_source": "Source",
        "w_h2": "Level 60 stat priority", "w_p": "Measured by the simulator on the character above: the DPS gained by one more point of each stat, with the same random draws on both sides. The relative value compares each stat with one point of {main}. Crit, hit and haste are counted per rating point, like Strength or Agility, so they compare directly; they respect the caps: hit at the cap adds nothing. A value near zero or negative is within the margin of error or tied to a limit (mana, cap).",
        "w_main_ap": "attack power", "w_main_sp": "spell power", "w_stat": "Stat", "w_per": "DPS gained", "w_rel": "Relative value", "w_unit_pt": "per point", "w_unit_pct": "per 1%", "w_unit_rating": "per rating point", "iv_stats_h3": "Icy Veins (level 30)", "w_none": "no effect",
        "stats": {"atkpwr": "Attack power", "splpwr": "Spell power", "str": "Strength", "agi": "Agility", "int": "Intellect", "spi": "Spirit", "critstrkrtng": "Crit", "hitrtng": "Hit", "hastertng": "Haste"},
        "note": "Talent data comes from the beta client. The level-60 build, gear, stats and rotation come from our simulator and are validated by DPS measurements; the rotation is compared with the Icy Veins guides, written for the level-30 beta. Healing is not simulated. This data will change with the beta and with the game's launch on November 4, 2026.",
        "w_tank": "For a tank the simulator does not weigh stats yet: Icy Veins' list (level 30) below remains the reference.",
    },
}

# healers: the client consumables that help healing and mana (healing is not simulated, so no measured gain)
HEALER_CONS = {
    "fr": ["Flacon de chagrin inflexible (+80 aux soins, régénération de mana)", "Parchemin d'intelligence et d'esprit", "Esprit de Zanza (+50 esprit)", "Juju de ruse (+30 intelligence)", "Potion de sang de mage (+12 mana / 5 s)", "Plat de soins (+55 aux soins)", "Nightfin Soup (+8 mana / 5 s) pour les longs combats"],
    "en": ["Flask of Unyielding Sorrow (+80 healing, mana regeneration)", "Scroll of Intellect and Spirit", "Spirit of Zanza (+50 spirit)", "Juju Guile (+30 intellect)", "Mageblood Potion (+12 mana / 5 s)", "Healing food (+55 healing)", "Nightfin Soup (+8 mana / 5 s) for long fights"],
}
