"""Texts of the level-60 DPS simulator page (/wow-forever/simulateur-dps/), FR + EN. Page JS strings live under `js`."""

TXT = {
    "fr": {
        "kicker": "World of Warcraft: Forever · Simulateur",
        "title": "Simulateur DPS niveau 60 WoW: Forever (Guerrier)",
        "desc": "Simulateur DPS niveau 60 WoW: Forever : équipement, buffs, talents, poids de stats et optimiseur d'équipement, des milliers de combats en secondes.",
        "h1": "Simulateur DPS niveau 60",
        "intro": "Un simulateur de combat complet dans votre navigateur : choisissez votre équipement, vos buffs et vos talents, lancez des milliers de combats, obtenez votre DPS, vos poids de stats et le meilleur équipement. Guerrier Fureur et Armes pour l'instant, les autres classes suivent.",
        "beta_note": "Version de travail avant le lancement du 4 novembre. Le moteur reprend les mécaniques de Classic (table d'attaque, formule de rage, armure) : tout ce qui n'est pas encore confirmé pour Forever est signalé « hypothèse » ci-dessous.",
        "h_char": "Personnage", "h_gear": "Équipement", "h_buffs": "Buffs, consommables et debuffs du boss", "h_talents": "Talents et rotation",
        "h_run": "Lancer", "h_results": "Résultats", "h_limits": "Limites connues",
        "class_spec": "Spécialisation", "race": "Race", "fight": "Durée du combat (s)", "iters": "Nombre de combats",
        "armor": "Armure du boss", "manual": "Stats saisies à la main (remplace le calcul)", "manual_hint": "Laissez vide pour calculer depuis l'équipement. Utile pour coller les valeurs de l'addon.",
        "ap": "Puissance d'attaque", "crit": "Critique %", "hit": "Toucher %",
        "empty": "(vide)", "mh": "Main droite", "oh": "Main gauche", "th": "Deux mains",
        "assumed": "hypothèse", "run": "Simuler", "weights": "Poids de stats", "optimize": "Optimiser l'équipement", "apply": "Appliquer cet équipement",
        "running": "Calcul en cours…", "workers": "{n} cœurs utilisés", "dps": "DPS moyen", "stdev": "Écart-type", "sem": "Marge d'erreur (±)",
        "ability": "Source", "share": "Part", "casts": "Lancers", "crits": "Critiques", "misses": "Ratés", "dodges": "Esquives", "uptime": "Uptime",
        "w_title": "Poids de stats (équivalent puissance d'attaque)", "w_crit": "1 % de critique", "w_hit": "1 % de toucher", "w_haste": "1 % de hâte",
        "o_title": "Meilleur équipement trouvé", "o_gain": "gain", "o_note": "L'optimiseur teste les objets de donjon connus de la bêta (niveau ≤ 60). Les objets de raid arriveront avec les données du jeu.",
        "execute": "Phase d'exécution (20 % de fin de combat)", "dw": "Mort désirée", "reck": "Témérité", "enrage": "Uptime d'Enrage (0 à 1)",
        "limits": [
            "Mécaniques reprises de Classic (formule de rage, table d'attaque face à un boss niveau 63, suppression de critique de 4,8 %, armure). Elles sont signalées « hypothèse » tant que Forever ne les confirme pas.",
            "Les valeurs de sorts viennent des tables du client de la bêta quand elles existent ; Exécution et Témérité utilisent encore les valeurs de Classic.",
            "Stats de base niveau 60 : valeurs de Classic non vérifiées ; vous pouvez saisir vos stats réelles à la main ou depuis l'addon.",
            "Objets : seules les données connues de la bêta (donjons, un peu de Cœur du Magma). Les effets déclenchés (procs d'armes, bijoux, bonus de panoplie) ne sont pas encore simulés.",
            "Pas encore simulé : cibles multiples, déplacements, mort du boss avant la fin, changements de posture, mana. Une cible, immobile, exécution sur les 20 derniers % du temps de combat.",
        ],
        "js": {
            "noItems": "Aucun objet", "run": "Simuler", "running": "Calcul en cours…", "done": "Terminé en {s} s ({rate} combats/s)",
            "optProgress": "Optimisation : {slot}…", "optDone": "Optimisation terminée en {s} s", "weightsRunning": "Calcul des poids…", "workers": "{n} cœurs",
        },
    },
    "en": {
        "kicker": "World of Warcraft: Forever · Simulator",
        "title": "Level 60 DPS simulator WoW: Forever (Warrior)",
        "desc": "Level 60 DPS simulator for WoW: Forever: gear, buffs, talents, stat weights and a gear optimizer, thousands of fights in a few seconds.",
        "h1": "Level 60 DPS simulator",
        "intro": "A full combat simulator in your browser: pick your gear, buffs and talents, run thousands of fights, get your DPS, your stat weights and the best gear. Fury and Arms Warrior for now, other classes to follow.",
        "beta_note": "Work in progress before the November 4 launch. The engine reuses Classic mechanics (attack table, rage formula, armor): anything not yet confirmed for Forever is marked \"assumed\" below.",
        "h_char": "Character", "h_gear": "Gear", "h_buffs": "Buffs, consumables and boss debuffs", "h_talents": "Talents and rotation",
        "h_run": "Run", "h_results": "Results", "h_limits": "Known limits",
        "class_spec": "Specialization", "race": "Race", "fight": "Fight length (s)", "iters": "Number of fights",
        "armor": "Boss armor", "manual": "Hand-entered stats (replaces the computation)", "manual_hint": "Leave empty to compute from gear. Handy to paste the addon's values.",
        "ap": "Attack power", "crit": "Crit %", "hit": "Hit %",
        "empty": "(empty)", "mh": "Main hand", "oh": "Off hand", "th": "Two-hand",
        "assumed": "assumed", "run": "Simulate", "weights": "Stat weights", "optimize": "Optimize gear", "apply": "Apply this gear",
        "running": "Running…", "workers": "{n} cores used", "dps": "Mean DPS", "stdev": "Std deviation", "sem": "Margin of error (±)",
        "ability": "Source", "share": "Share", "casts": "Casts", "crits": "Crits", "misses": "Misses", "dodges": "Dodges", "uptime": "Uptime",
        "w_title": "Stat weights (attack power equivalent)", "w_crit": "1% crit", "w_hit": "1% hit", "w_haste": "1% haste",
        "o_title": "Best gear found", "o_gain": "gain", "o_note": "The optimizer tests the beta's known dungeon items (level ≤ 60). Raid items will come with the game's data.",
        "execute": "Execute phase (last 20% of the fight)", "dw": "Death Wish", "reck": "Recklessness", "enrage": "Enrage uptime (0 to 1)",
        "limits": [
            "Mechanics taken from Classic (rage formula, attack table against a level-63 boss, 4.8% crit suppression, armor). They are marked \"assumed\" until Forever confirms them.",
            "Spell values come from the beta client tables when they exist; Execute and Recklessness still use Classic values.",
            "Level 60 base stats: unverified Classic values; you can enter your real stats by hand or from the addon.",
            "Items: only the data known from the beta (dungeons, a little Molten Core). Proc effects (weapon procs, trinkets, set bonuses) are not simulated yet.",
            "Not simulated yet: multiple targets, movement, boss dying before the end, stance changes, mana. One stationary target, execute on the last 20% of the fight time.",
        ],
        "js": {
            "noItems": "No item", "run": "Simulate", "running": "Running…", "done": "Done in {s} s ({rate} fights/s)",
            "optProgress": "Optimizing: {slot}…", "optDone": "Optimization done in {s} s", "weightsRunning": "Computing weights…", "workers": "{n} cores",
        },
    },
}
